/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HumanInteractionForm.java
 *
 * Created on 20-Oct-2010, 21:01:52
 */

package gui.form.supplement;

import global.Global;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import process_model.supplement.Supplements;
import process_model.supplement.human_interaction.Analyst;
import process_model.supplement.human_interaction.HumanInteraction;
import toolbox.Tools;

/**
 *
 * @author amb04
 */
public class HumanInteractionForm extends javax.swing.JFrame {

/** Creates new form HumanInteractionForm */
private Analyst analyst=null;
private String analystRole[]={"","Biologist",
                                 "Computer Scientist",
                                 "Data Miner",
                                 "Domain Expert",
                                 "Lab Technician",
                                 "Statistician",
                                 "Other"};

private String analystLevel[]={"","Beginner", 
                                  "Normal",
                                  "Professional"};

    public HumanInteractionForm() {
        initComponents();        
      this.setTitle("Human Interaction");
      if (Global.project.getSupplements()==null)
          Global.project.setSupplements(new Supplements());

      if (Global.project.getSupplements().getHumanInteraction() ==null)
          Global.project.getSupplements().setHumanInteraction(new HumanInteraction());
      //
      this.refresh_analyst();
      this.populate_analyst();
      this.setVisible(true);
    }

    public HumanInteractionForm(Analyst selectedAnalyst) {
      initComponents();
      this.setTitle("Human Interaction");

      if (Global.project.getSupplements()==null)
          Global.project.setSupplements(new Supplements());

      if (Global.project.getSupplements().getHumanInteraction() ==null)
          Global.project.getSupplements().setHumanInteraction(new HumanInteraction());
      //
      if (selectedAnalyst!=null)
          this.analyst=selectedAnalyst;
      else
          this.refresh_analyst();
      //
      this.populate_analyst();
      this.setVisible(true);
    }

/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reporting_Customised_jDesktopPane3 = new javax.swing.JDesktopPane();
        CustomisedReport_jDesktopPane3 = new javax.swing.JDesktopPane();
        Add_jButton = new javax.swing.JButton();
        Delete_jButton = new javax.swing.JButton();
        Save_jButton = new javax.swing.JButton();
        New_jButton = new javax.swing.JButton();
        Refresh_jButton = new javax.swing.JButton();
        Last_jButton = new javax.swing.JButton();
        Next_jButton = new javax.swing.JButton();
        Previous_jButton = new javax.swing.JButton();
        First_jButton = new javax.swing.JButton();
        Load_jButton = new javax.swing.JButton();
        Planning_Planner_info_jDesktopPane = new javax.swing.JDesktopPane();
        Analyst_Name_jLabel = new javax.swing.JLabel();
        Analyst_Contacts_jLabel = new javax.swing.JLabel();
        jScrollPane62 = new javax.swing.JScrollPane();
        Analyst_Contacts_jTextArea = new javax.swing.JTextArea();
        Analyst_Role_jComboBox = new javax.swing.JComboBox();
        Analyst_Level_jLabel = new javax.swing.JLabel();
        Analyst_Level_jComboBox = new javax.swing.JComboBox();
        Analyst_Role_jLabel = new javax.swing.JLabel();
        Analyst_Name_jTextField = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Phase_Save_jMenuItem = new javax.swing.JMenuItem();
        Phase_SaveAs_jMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Phase_Load_jMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        Phase_Close_jMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Human Interaction");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Reporting_Customised_jDesktopPane3.setBackground(new java.awt.Color(255, 255, 204));
        Reporting_Customised_jDesktopPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Mining Process Actors"));
        Reporting_Customised_jDesktopPane3.setName("Reporting_Customised_jDesktopPane3"); // NOI18N

        CustomisedReport_jDesktopPane3.setBackground(new java.awt.Color(255, 255, 153));
        CustomisedReport_jDesktopPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CustomisedReport_jDesktopPane3.setName("CustomisedReport_jDesktopPane3"); // NOI18N

        Add_jButton.setText("Add +");
        Add_jButton.setName("Add_jButton"); // NOI18N
        Add_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_jButtonActionPerformed(evt);
            }
        });
        Add_jButton.setBounds(190, 50, 100, 25);
        CustomisedReport_jDesktopPane3.add(Add_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Delete_jButton.setText("Delete");
        Delete_jButton.setName("Delete_jButton"); // NOI18N
        Delete_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_jButtonActionPerformed(evt);
            }
        });
        Delete_jButton.setBounds(290, 50, 100, 25);
        CustomisedReport_jDesktopPane3.add(Delete_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Save_jButton.setText("Save");
        Save_jButton.setName("Save_jButton"); // NOI18N
        Save_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_jButtonActionPerformed(evt);
            }
        });
        Save_jButton.setBounds(90, 50, 100, 25);
        CustomisedReport_jDesktopPane3.add(Save_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        New_jButton.setText("New");
        New_jButton.setName("New_jButton"); // NOI18N
        New_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_jButtonActionPerformed(evt);
            }
        });
        New_jButton.setBounds(10, 50, 80, 25);
        CustomisedReport_jDesktopPane3.add(New_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Refresh_jButton.setText("Refresh");
        Refresh_jButton.setName("Refresh_jButton"); // NOI18N
        Refresh_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_jButtonActionPerformed(evt);
            }
        });
        Refresh_jButton.setBounds(390, 50, 80, 25);
        CustomisedReport_jDesktopPane3.add(Refresh_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Last_jButton.setText("Last >>");
        Last_jButton.setName("Last_jButton"); // NOI18N
        Last_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Last_jButtonActionPerformed(evt);
            }
        });
        Last_jButton.setBounds(290, 20, 100, 25);
        CustomisedReport_jDesktopPane3.add(Last_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Next_jButton.setText("Next >");
        Next_jButton.setName("Next_jButton"); // NOI18N
        Next_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_jButtonActionPerformed(evt);
            }
        });
        Next_jButton.setBounds(210, 20, 80, 25);
        CustomisedReport_jDesktopPane3.add(Next_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Previous_jButton.setText("< Previous");
        Previous_jButton.setName("Previous_jButton"); // NOI18N
        Previous_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Previous_jButtonActionPerformed(evt);
            }
        });
        Previous_jButton.setBounds(110, 20, 100, 25);
        CustomisedReport_jDesktopPane3.add(Previous_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        First_jButton.setText("<< First");
        First_jButton.setName("First_jButton"); // NOI18N
        First_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                First_jButtonActionPerformed(evt);
            }
        });
        First_jButton.setBounds(10, 20, 100, 25);
        CustomisedReport_jDesktopPane3.add(First_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Load_jButton.setText("Load");
        Load_jButton.setName("Load_jButton"); // NOI18N
        Load_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Load_jButtonActionPerformed(evt);
            }
        });
        Load_jButton.setBounds(390, 20, 80, 25);
        CustomisedReport_jDesktopPane3.add(Load_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CustomisedReport_jDesktopPane3.setBounds(30, 380, 480, 90);
        Reporting_Customised_jDesktopPane3.add(CustomisedReport_jDesktopPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_info_jDesktopPane.setBackground(new java.awt.Color(255, 255, 153));
        Planning_Planner_info_jDesktopPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Planning_Planner_info_jDesktopPane.setName("Planning_Planner_info_jDesktopPane"); // NOI18N

        Analyst_Name_jLabel.setText("Name");
        Analyst_Name_jLabel.setName("Analyst_Name_jLabel"); // NOI18N
        Analyst_Name_jLabel.setBounds(20, 10, 210, 20);
        Planning_Planner_info_jDesktopPane.add(Analyst_Name_jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Analyst_Contacts_jLabel.setText("Contact Details (Comma separated)");
        Analyst_Contacts_jLabel.setName("Analyst_Contacts_jLabel"); // NOI18N
        Analyst_Contacts_jLabel.setBounds(20, 90, 210, 20);
        Planning_Planner_info_jDesktopPane.add(Analyst_Contacts_jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane62.setName("jScrollPane62"); // NOI18N

        Analyst_Contacts_jTextArea.setColumns(20);
        Analyst_Contacts_jTextArea.setRows(5);
        Analyst_Contacts_jTextArea.setName("Analyst_Contacts_jTextArea"); // NOI18N
        jScrollPane62.setViewportView(Analyst_Contacts_jTextArea);

        jScrollPane62.setBounds(20, 110, 430, 120);
        Planning_Planner_info_jDesktopPane.add(jScrollPane62, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Analyst_Role_jComboBox.setModel(new DefaultComboBoxModel(this.analystRole));
        Analyst_Role_jComboBox.setName("Analyst_Role_jComboBox"); // NOI18N
        Analyst_Role_jComboBox.setBounds(20, 270, 200, 20);
        Planning_Planner_info_jDesktopPane.add(Analyst_Role_jComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Analyst_Level_jLabel.setText("Level");
        Analyst_Level_jLabel.setName("Analyst_Level_jLabel"); // NOI18N
        Analyst_Level_jLabel.setBounds(260, 250, 160, 20);
        Planning_Planner_info_jDesktopPane.add(Analyst_Level_jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Analyst_Level_jComboBox.setModel(new DefaultComboBoxModel(this.analystLevel));
        Analyst_Level_jComboBox.setName("Analyst_Level_jComboBox"); // NOI18N
        Analyst_Level_jComboBox.setBounds(260, 270, 190, 20);
        Planning_Planner_info_jDesktopPane.add(Analyst_Level_jComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Analyst_Role_jLabel.setText("Role");
        Analyst_Role_jLabel.setName("Analyst_Role_jLabel"); // NOI18N
        Analyst_Role_jLabel.setBounds(20, 250, 170, 20);
        Planning_Planner_info_jDesktopPane.add(Analyst_Role_jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Analyst_Name_jTextField.setName("Analyst_Name_jTextField"); // NOI18N
        Analyst_Name_jTextField.setBounds(20, 30, 430, 30);
        Planning_Planner_info_jDesktopPane.add(Analyst_Name_jTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_info_jDesktopPane.setBounds(30, 40, 480, 320);
        Reporting_Customised_jDesktopPane3.add(Planning_Planner_info_jDesktopPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu3.setText("File");
        jMenu3.setName("jMenu3"); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jSeparator3.setName("jSeparator3"); // NOI18N
        jMenu3.add(jSeparator3);

        Phase_Save_jMenuItem.setText("Save");
        Phase_Save_jMenuItem.setName("Phase_Save_jMenuItem"); // NOI18N
        Phase_Save_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phase_Save_jMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(Phase_Save_jMenuItem);

        Phase_SaveAs_jMenuItem.setText("Sava As");
        Phase_SaveAs_jMenuItem.setName("Phase_SaveAs_jMenuItem"); // NOI18N
        Phase_SaveAs_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phase_SaveAs_jMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(Phase_SaveAs_jMenuItem);

        jSeparator1.setName("jSeparator1"); // NOI18N
        jMenu3.add(jSeparator1);

        Phase_Load_jMenuItem.setText("Load ");
        Phase_Load_jMenuItem.setName("Phase_Load_jMenuItem"); // NOI18N
        Phase_Load_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phase_Load_jMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(Phase_Load_jMenuItem);

        jSeparator2.setName("jSeparator2"); // NOI18N
        jMenu3.add(jSeparator2);

        menuBar.add(jMenu3);

        jMenu1.setText("Exit");
        jMenu1.setName("jMenu1"); // NOI18N

        Phase_Close_jMenuItem.setText("Close");
        Phase_Close_jMenuItem.setName("Phase_Close_jMenuItem"); // NOI18N
        Phase_Close_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phase_Close_jMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(Phase_Close_jMenuItem);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Reporting_Customised_jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Reporting_Customised_jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_jButtonActionPerformed
        this.save_analyst();
        this.clear_analyst();
}//GEN-LAST:event_Add_jButtonActionPerformed

    private void Save_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_jButtonActionPerformed
        this.save_analyst();
}//GEN-LAST:event_Save_jButtonActionPerformed

    private void Refresh_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_jButtonActionPerformed
        this.refresh_analyst();
}//GEN-LAST:event_Refresh_jButtonActionPerformed

    private void First_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_First_jButtonActionPerformed
    this.first_analyst();
    }//GEN-LAST:event_First_jButtonActionPerformed

    private void Previous_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Previous_jButtonActionPerformed
        this.previous_analyst();
    }//GEN-LAST:event_Previous_jButtonActionPerformed

    private void Next_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_jButtonActionPerformed
        this.next_analyst();
    }//GEN-LAST:event_Next_jButtonActionPerformed

    private void Last_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Last_jButtonActionPerformed
        this.last_analyst();
    }//GEN-LAST:event_Last_jButtonActionPerformed

    private void New_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_jButtonActionPerformed
        this.clear_analyst();
    }//GEN-LAST:event_New_jButtonActionPerformed

    private void Delete_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_jButtonActionPerformed
        this.delete_analyst();
    }//GEN-LAST:event_Delete_jButtonActionPerformed

    private void Load_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Load_jButtonActionPerformed

    if (Global.project!=null && Global.project.getSupplements()==null)
        Global.project.setSupplements(new Supplements());

    HumanInteraction humanInteraction= new HumanInteraction().open();
    if (humanInteraction!=null)
        Global.project.getSupplements().setHumanInteraction(humanInteraction);

    //
    this.refresh_analyst();
    //
    this.populate_analyst();
    //
    }//GEN-LAST:event_Load_jButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
   this.save_analyst();
    }//GEN-LAST:event_formWindowClosed

    private void Phase_Load_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phase_Load_jMenuItemActionPerformed
    this.Load_jButtonActionPerformed(evt);
}//GEN-LAST:event_Phase_Load_jMenuItemActionPerformed

    private void Phase_Save_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phase_Save_jMenuItemActionPerformed
        this.save_analyst();
}//GEN-LAST:event_Phase_Save_jMenuItemActionPerformed

    private void Phase_SaveAs_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phase_SaveAs_jMenuItemActionPerformed
        if (Global.project !=null && Global.project.getSupplements()!=null &&
                Global.project.getSupplements().getHumanInteraction()!=null) {
            File selectedFile =Tools.chooseFile("Choose Location", null, Global.project.getLocation(), true);
            String selectedFileString = (selectedFile != null) ? selectedFile.getPath() : null;

            if (selectedFileString!=null)
                Global.project.getSupplements().getHumanInteraction().store(selectedFileString);
        }
}//GEN-LAST:event_Phase_SaveAs_jMenuItemActionPerformed

    private void Phase_Close_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phase_Close_jMenuItemActionPerformed
        this.Save_jButtonActionPerformed(evt);
        this.dispose();
}//GEN-LAST:event_Phase_Close_jMenuItemActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jMenu3ActionPerformed
//LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HumanInteractionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_jButton;
    private javax.swing.JLabel Analyst_Contacts_jLabel;
    private javax.swing.JTextArea Analyst_Contacts_jTextArea;
    private javax.swing.JComboBox Analyst_Level_jComboBox;
    private javax.swing.JLabel Analyst_Level_jLabel;
    private javax.swing.JLabel Analyst_Name_jLabel;
    private javax.swing.JTextField Analyst_Name_jTextField;
    private javax.swing.JComboBox Analyst_Role_jComboBox;
    private javax.swing.JLabel Analyst_Role_jLabel;
    private javax.swing.JDesktopPane CustomisedReport_jDesktopPane3;
    private javax.swing.JButton Delete_jButton;
    private javax.swing.JButton First_jButton;
    private javax.swing.JButton Last_jButton;
    private javax.swing.JButton Load_jButton;
    private javax.swing.JButton New_jButton;
    private javax.swing.JButton Next_jButton;
    private javax.swing.JMenuItem Phase_Close_jMenuItem;
    private javax.swing.JMenuItem Phase_Load_jMenuItem;
    private javax.swing.JMenuItem Phase_SaveAs_jMenuItem;
    private javax.swing.JMenuItem Phase_Save_jMenuItem;
    private javax.swing.JDesktopPane Planning_Planner_info_jDesktopPane;
    private javax.swing.JButton Previous_jButton;
    private javax.swing.JButton Refresh_jButton;
    private javax.swing.JDesktopPane Reporting_Customised_jDesktopPane3;
    private javax.swing.JButton Save_jButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JScrollPane jScrollPane62;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables


//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
//****************************************************************************
//                              Save Resource
//****************************************************************************
//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

 private void save_analyst()
 {
       try
         {
            if (this.analyst==null)
                this.analyst=new Analyst();
             //
             if(this.Analyst_Name_jTextField!=null
             && !this.Analyst_Name_jTextField.getText().equals(""))
                this.analyst.setName(this.Analyst_Name_jTextField.getText());
             //
             if(this.Analyst_Contacts_jTextArea!=null
             && !this.Analyst_Contacts_jTextArea.getText().equals(""))
                this.analyst.setContactDetails(this.Analyst_Contacts_jTextArea.getText());
             //
             this.analyst.setRole(this.Analyst_Role_jComboBox.getSelectedIndex());

             this.analyst.setLevel(this.Analyst_Level_jComboBox.getSelectedIndex());

             Global.project.getSupplements().getHumanInteraction().save(analyst);
             Global.project.getSupplements().getHumanInteraction().store(null);

         } catch (Exception ex) {
                Logger.getLogger(ManagementForm.class.getName()).log(Level.SEVERE, null, ex);
         }
  }



 //RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
//****************************************************************************
//                              Refresh
//****************************************************************************
//RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR

 private void refresh_analyst()
 {
    if (Global.project!=null &&
        Global.project.getSupplements() !=null &&
        Global.project.getSupplements().getHumanInteraction()!=null &&
        Global.project.getSupplements().getHumanInteraction().getAnalystsList().size()>0 )
    {
        this.analyst = Global.project.getSupplements().getHumanInteraction().getFirst();
        this.populate_analyst();
    }

}


//DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
//****************************************************************************
//                              Delete Resource
//DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
//****************************************************************************
 private void delete_analyst()
    {
    int index= Global.project.getSupplements().getHumanInteraction().getAnalystsList().indexOf(this.analyst);
    if (this.analyst!=null && Global.project.getSupplements().getHumanInteraction()!=null)
        if (Global.project.getSupplements().getHumanInteraction().delete(this.analyst)==0);
        {
            if (Global.project.getSupplements().getHumanInteraction().getAnalystsList().size()>0)
            {
                if (index==0)
                    this.analyst = Global.project.getSupplements().getHumanInteraction().get(index);
                else
                    this.analyst = Global.project.getSupplements().getHumanInteraction().get(index-1);

                this.populate_analyst();
            }
            else
            this.clear_analyst();
        }

     this.save_analyst();     
 }

//CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
//****************************************************************************
//                     Clear Source Resource & Source
//****************************************************************************
 //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

 private void clear_analystForm()
{
     this.Analyst_Name_jTextField.setText("");
     this.Analyst_Contacts_jTextArea.setText("");
     this.Analyst_Role_jComboBox.setSelectedIndex(0);
     this.Analyst_Level_jComboBox.setSelectedIndex(0);
 }

 //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 //                              Clear Source
 //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 private void clear_analyst( )
{
     this.clear_analystForm();     
     this.analyst=null;
 }

//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
//****************************************************************************
//                             Populate
//****************************************************************************
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP

private void populateForm()
{ 
    this.repaint();
    this.pack();
}


//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
//                         Populate Resource Form
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
 private void populate_analyst()
{         
         if (analyst!=null && analyst.getName()!=null)
            this.Analyst_Name_jTextField.setText(analyst.getName());
         else
           this.Analyst_Name_jTextField.setText("");
         //--------------------------------------------------------------------
         if (analyst!=null && analyst.getContactDetails()!=null)
            this.Analyst_Contacts_jTextArea.setText(analyst.getContactDetails());
         else
           this.Analyst_Contacts_jTextArea.setText("");
         //--------------------------------------------------------------------
         if (analyst!=null && analyst.getLevel()!=null)
            this.Analyst_Level_jComboBox.setSelectedIndex(analyst.getLevel().ordinal()+1);
         else
             this.Analyst_Level_jComboBox.setSelectedIndex(0);
         //--------------------------------------------------------------------
         if (analyst!=null && analyst.getRole()!=null)
            this.Analyst_Role_jComboBox.setSelectedIndex(analyst.getRole().ordinal()+1);
         else
             this.Analyst_Role_jComboBox.setSelectedIndex(0);
 
     this.populateForm();
 }


//FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
//****************************************************************************
//                            First & Last Resource
//****************************************************************************
//FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

 private void first_analyst()
    {
     if (Global.project.getSupplements().getHumanInteraction()!=null)
     {
         this.save_analyst();
         this.analyst=Global.project.getSupplements().getHumanInteraction().getFirst();
     }

     this.populate_analyst();

 }

 //****************************************************************************
 private void last_analyst()
    {
     if (Global.project.getSupplements().getHumanInteraction()!=null)
     {
         this.save_analyst();
         this.analyst=Global.project.getSupplements().getHumanInteraction().getLast();         
     }

     this.populate_analyst();

 }

//NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
//****************************************************************************
//                     Next Resource & Source
//****************************************************************************
//NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 private void next_analyst()
    {
      if(Global.project.getSupplements().getHumanInteraction()!=null)
        {
            if (this.analyst!=null)
            {
                if (Global.project.getSupplements().getHumanInteraction().getNext(this.analyst)!=null)
                {
                    this.save_analyst();
                    this.analyst=Global.project.getSupplements().getHumanInteraction().getNext(this.analyst);
                    this.populate_analyst();

                }
            }
        }
        //else
            //System.out.print("No Phase PreRequisits is found yet ");
    }

//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
//****************************************************************************
//                     Previous Resource& Source
//****************************************************************************
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
 private void previous_analyst()
    {
      if(Global.project.getSupplements().getHumanInteraction()!=null)
        {
            if (this.analyst!=null)
            {
                if (Global.project.getSupplements().getHumanInteraction().getPrevious(this.analyst)!=null)
                {
                    this.save_analyst();
                    this.analyst=Global.project.getSupplements().getHumanInteraction().getPrevious(this.analyst);
                    this.populate_analyst();

                }
            }
        }
       // else
            //System.out.print("No Phase PreRequisits is found yet ");
    }




}
