/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManagementForm.java
 *
 * Created on 04-Sep-2010, 19:46:37
 */

package gui.form.supplement;

import global.Global;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import process_model.supplement.Supplements;
import process_model.supplement.management.Management;
import process_model.supplement.management.constraint.Constraints;
import process_model.supplement.management.requirment.Requirements;
import process_model.supplement.management.resource.Resource;
import process_model.supplement.management.resource.Resources;
import toolbox.Tools;

/**
 *
 * @author amb04
 */
public class ManagementForm extends javax.swing.JFrame {

    /** Creates new form ManagementForm */
    private Resource resource=null;    
    private Resource requirement=null;    
    private Constraints constraint=null;
    private String resourceTypeArray[]={"","Hardware",
                                           "Software",
                                           "Human Expertise",
                                           "Other"};
    public ManagementForm() {
      initComponents();

      this.setVisible(true);
      
      if (Global.project.getSupplements()==null)
          Global.project.setSupplements(new Supplements());

      if (Global.project.getSupplements().getManagement()==null)
        Global.project.getSupplements().setManagement(new Management());

      if (Global.project.getSupplements().getManagement().getResources()==null)
        Global.project.getSupplements().getManagement().setResources(new Resources());
      this.refresh_resource();
      this.populate_resource();
      //
      this.refresh_constraints();
      this.populate_constraint();
      //

      if (Global.project!=null)
          this.setTitle("Project Management         "+Global.project.toString());
      this.populateForm();
    }    

  public ManagementForm(Resource passedResource) {
      initComponents();
      this.setVisible(true);
      if (Global.project.getSupplements()==null)
          Global.project.setSupplements(new Supplements());

      if (Global.project.getSupplements().getManagement()==null)
          Global.project.getSupplements().setManagement(new Management());
      //
      if (Global.project.getSupplements().getManagement().getResources()==null)
          Global.project.getSupplements().getManagement().setResources(new Resources());
      //
      if (passedResource!=null)
          this.resource=passedResource;
      else
          this.refresh_resource();
      //
      this.populate_resource();
      this.refresh_constraints();
      this.populate_constraint();
      if (Global.project!=null)
         this.setTitle("Project Management         "+Global.project.toString());
      this.populateForm();      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane26 = new javax.swing.JDesktopPane();
        jTextField64 = new javax.swing.JTextField();
        jLabel121 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        Prerequisite_Source_jDesktopPane = new javax.swing.JDesktopPane();
        Project_jTabbedPane = new javax.swing.JTabbedPane();
        Resource_jDesktopPane = new javax.swing.JDesktopPane();
        Project_Resources_jDesktopPane = new javax.swing.JDesktopPane();
        CustomisedReport_jDesktopPane1 = new javax.swing.JDesktopPane();
        Resource_Delete_jButton = new javax.swing.JButton();
        Resource_Save_jButton = new javax.swing.JButton();
        Resource_New_jButton = new javax.swing.JButton();
        Resource_Refresh_jButton = new javax.swing.JButton();
        Resource_Last_jButton = new javax.swing.JButton();
        Resource_Next_jButton = new javax.swing.JButton();
        Resource_Previous_jButton = new javax.swing.JButton();
        Resource_First_jButton = new javax.swing.JButton();
        Resource_Add_jButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resource_Description_jTextArea = new javax.swing.JTextArea();
        Planning_Project_Resource_Type_jLabel = new javax.swing.JLabel();
        Resource_Type_jComboBox = new javax.swing.JComboBox();
        Resource_Cost_jTextField = new javax.swing.JTextField();
        Resource_Cost_jLabel = new javax.swing.JLabel();
        Planning_ProjectResource_Req_jDesktopPane1 = new javax.swing.JDesktopPane();
        Planning_ProjectResourceReqType_jLabel1 = new javax.swing.JLabel();
        Resource_Req_Type_jComboBox = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        Resource_Req_Description_jTextArea = new javax.swing.JTextArea();
        CustomisedReport_jDesktopPane4 = new javax.swing.JDesktopPane();
        Resource_Req_Add_jButton = new javax.swing.JButton();
        Resource_Req__Delete_jButton = new javax.swing.JButton();
        Resource_Req_Save_jButton = new javax.swing.JButton();
        Resource_Req_Refresh_jButton = new javax.swing.JButton();
        Resource_Req_Next_jButton = new javax.swing.JButton();
        Resource_Req_Previous_jButton1 = new javax.swing.JButton();
        Resource_Req_Cost_jTextField = new javax.swing.JTextField();
        Resource_Req_Cost_jLabel = new javax.swing.JLabel();
        Constraint_jDesktopPane = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        Reporting_Customised_jDesktopPane1 = new javax.swing.JDesktopPane();
        Reporting_Customised_jDesktopPane2 = new javax.swing.JDesktopPane();
        Project_Constraint_AvailableDuration_jLabel = new javax.swing.JLabel();
        Project_Constraint_ElapsedDuration_jLabel1 = new javax.swing.JLabel();
        Constraint_ElapsedTime_jTextField = new javax.swing.JTextField();
        Constraint_TotalDuration_jTextField = new javax.swing.JTextField();
        Reporting_Customised_jDesktopPane4 = new javax.swing.JDesktopPane();
        Constraint_RemainingTime_jTextField = new javax.swing.JTextField();
        Project_Constraint_RemainingDuration_jLabel1 = new javax.swing.JLabel();
        Reporting_Customised_jDesktopPane3 = new javax.swing.JDesktopPane();
        Reporting_Customised_jDesktopPane5 = new javax.swing.JDesktopPane();
        Project_Constraint_AvailableFunds_jLabel = new javax.swing.JLabel();
        Constraint_TotalFunds_jTextField = new javax.swing.JTextField();
        Project_Constraint_UsedFunds_jLabel = new javax.swing.JLabel();
        Constraint_UsedFunds_jTextField = new javax.swing.JTextField();
        Reporting_Customised_jDesktopPane6 = new javax.swing.JDesktopPane();
        Project_Constraint_RemainingFunds_jLabel1 = new javax.swing.JLabel();
        Constraint_RemainingFunds_jTextField = new javax.swing.JTextField();
        Reporting_Customised_jDesktopPane7 = new javax.swing.JDesktopPane();
        Reporting_Customised_jDesktopPane10 = new javax.swing.JDesktopPane();
        Constraint_Save_jButton = new javax.swing.JButton();
        Constraint_Refresh_jButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Phase_Save_jMenuItem = new javax.swing.JMenuItem();
        Phase_SaveAs_jMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        Phase_Close_jMenuItem = new javax.swing.JMenuItem();

        jDesktopPane26.setBackground(new java.awt.Color(255, 255, 204));
        jDesktopPane26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField64.setBounds(80, 10, 530, 30);
        jDesktopPane26.add(jTextField64, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel121.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel121.setText("Supporting Evidence");
        jLabel121.setBounds(10, 50, 150, 20);
        jDesktopPane26.add(jLabel121, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel127.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel127.setText("Rational");
        jLabel127.setBounds(10, 10, 60, 20);
        jDesktopPane26.add(jLabel127, javax.swing.JLayeredPane.DEFAULT_LAYER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Prerequisite_Source_jDesktopPane.setBackground(new java.awt.Color(255, 255, 153));
        Prerequisite_Source_jDesktopPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Resource_jDesktopPane.setBackground(new java.awt.Color(255, 255, 204));
        Resource_jDesktopPane.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Resource_jDesktopPaneFocusGained(evt);
            }
        });

        Project_Resources_jDesktopPane.setBackground(new java.awt.Color(255, 255, 204));
        Project_Resources_jDesktopPane.setBorder(javax.swing.BorderFactory.createTitledBorder(" Project Resources "));

        CustomisedReport_jDesktopPane1.setBackground(new java.awt.Color(255, 255, 153));
        CustomisedReport_jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Resource_Delete_jButton.setText("Delete");
        Resource_Delete_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resource_Delete_jButtonActionPerformed(evt);
            }
        });
        Resource_Delete_jButton.setBounds(670, 10, 80, 23);
        CustomisedReport_jDesktopPane1.add(Resource_Delete_jButton, javax.swing.JLayeredPane.MODAL_LAYER);

        Resource_Save_jButton.setText("Save");
        Resource_Save_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resource_Save_jButtonActionPerformed(evt);
            }
        });
        Resource_Save_jButton.setBounds(520, 10, 70, 23);
        CustomisedReport_jDesktopPane1.add(Resource_Save_jButton, javax.swing.JLayeredPane.MODAL_LAYER);

        Resource_New_jButton.setText("New");
        Resource_New_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resource_New_jButtonActionPerformed(evt);
            }
        });
        Resource_New_jButton.setBounds(460, 10, 60, 23);
        CustomisedReport_jDesktopPane1.add(Resource_New_jButton, javax.swing.JLayeredPane.MODAL_LAYER);

        Resource_Refresh_jButton.setText("Refresh");
        Resource_Refresh_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resource_Refresh_jButtonActionPerformed(evt);
            }
        });
        Resource_Refresh_jButton.setBounds(370, 10, 90, 23);
        CustomisedReport_jDesktopPane1.add(Resource_Refresh_jButton, javax.swing.JLayeredPane.MODAL_LAYER);

        Resource_Last_jButton.setText("Last >>");
        Resource_Last_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resource_Last_jButtonActionPerformed(evt);
            }
        });
        Resource_Last_jButton.setBounds(280, 10, 90, 23);
        CustomisedReport_jDesktopPane1.add(Resource_Last_jButton, javax.swing.JLayeredPane.MODAL_LAYER);

        Resource_Next_jButton.setText("Next >");
        Resource_Next_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resource_Next_jButtonActionPerformed(evt);
            }
        });
        Resource_Next_jButton.setBounds(200, 10, 80, 23);
        CustomisedReport_jDesktopPane1.add(Resource_Next_jButton, javax.swing.JLayeredPane.MODAL_LAYER);

        Resource_Previous_jButton.setText("< Previous");
        Resource_Previous_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resource_Previous_jButtonActionPerformed(evt);
            }
        });
        Resource_Previous_jButton.setBounds(100, 10, 100, 23);
        CustomisedReport_jDesktopPane1.add(Resource_Previous_jButton, javax.swing.JLayeredPane.MODAL_LAYER);

        Resource_First_jButton.setText("<< First");
        Resource_First_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resource_First_jButtonActionPerformed(evt);
            }
        });
        Resource_First_jButton.setBounds(10, 10, 90, 23);
        CustomisedReport_jDesktopPane1.add(Resource_First_jButton, javax.swing.JLayeredPane.MODAL_LAYER);

        Resource_Add_jButton.setText("Add+");
        Resource_Add_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resource_Add_jButtonActionPerformed(evt);
            }
        });
        Resource_Add_jButton.setBounds(600, 10, 70, 23);
        CustomisedReport_jDesktopPane1.add(Resource_Add_jButton, javax.swing.JLayeredPane.MODAL_LAYER);

        CustomisedReport_jDesktopPane1.setBounds(20, 420, 760, 40);
        Project_Resources_jDesktopPane.add(CustomisedReport_jDesktopPane1, javax.swing.JLayeredPane.MODAL_LAYER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Resource_Description_jTextArea.setColumns(20);
        Resource_Description_jTextArea.setRows(5);
        jScrollPane1.setViewportView(Resource_Description_jTextArea);

        Planning_Project_Resource_Type_jLabel.setText("Type");

        Resource_Type_jComboBox.setModel(new DefaultComboBoxModel(this.resourceTypeArray));

        Resource_Cost_jLabel.setText("Cost");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Planning_Project_Resource_Type_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Resource_Type_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                        .addComponent(Resource_Cost_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Resource_Cost_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Resource_Cost_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Planning_Project_Resource_Type_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resource_Type_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resource_Cost_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBounds(20, 20, 760, 160);
        Project_Resources_jDesktopPane.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_ProjectResource_Req_jDesktopPane1.setBackground(new java.awt.Color(255, 255, 102));
        Planning_ProjectResource_Req_jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resource Requirements"));

        Planning_ProjectResourceReqType_jLabel1.setText("Requirment Type");
        Planning_ProjectResourceReqType_jLabel1.setBounds(20, 130, 130, 22);
        Planning_ProjectResource_Req_jDesktopPane1.add(Planning_ProjectResourceReqType_jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Resource_Req_Type_jComboBox.setModel(new DefaultComboBoxModel(this.resourceTypeArray));
        Resource_Req_Type_jComboBox.setBounds(150, 130, 200, 22);
        Planning_ProjectResource_Req_jDesktopPane1.add(Resource_Req_Type_jComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Resource_Req_Description_jTextArea.setColumns(20);
        Resource_Req_Description_jTextArea.setRows(5);
        jScrollPane2.setViewportView(Resource_Req_Description_jTextArea);

        jScrollPane2.setBounds(20, 20, 730, 90);
        Planning_ProjectResource_Req_jDesktopPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CustomisedReport_jDesktopPane4.setBackground(new java.awt.Color(255, 255, 102));
        CustomisedReport_jDesktopPane4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Resource_Req_Add_jButton.setText("Add+");
        Resource_Req_Add_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resource_Req_Add_jButtonActionPerformed(evt);
            }
        });
        Resource_Req_Add_jButton.setBounds(470, 10, 90, 21);
        CustomisedReport_jDesktopPane4.add(Resource_Req_Add_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Resource_Req__Delete_jButton.setText("Delete");
        Resource_Req__Delete_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resource_Req__Delete_jButtonActionPerformed(evt);
            }
        });
        Resource_Req__Delete_jButton.setBounds(610, 10, 100, 21);
        CustomisedReport_jDesktopPane4.add(Resource_Req__Delete_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Resource_Req_Save_jButton.setText("Save");
        Resource_Req_Save_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resource_Req_Save_jButtonActionPerformed(evt);
            }
        });
        Resource_Req_Save_jButton.setBounds(380, 10, 90, 21);
        CustomisedReport_jDesktopPane4.add(Resource_Req_Save_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Resource_Req_Refresh_jButton.setText("Refresh");
        Resource_Req_Refresh_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resource_Req_Refresh_jButtonActionPerformed(evt);
            }
        });
        Resource_Req_Refresh_jButton.setBounds(240, 10, 100, 21);
        CustomisedReport_jDesktopPane4.add(Resource_Req_Refresh_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Resource_Req_Next_jButton.setText("Next >");
        Resource_Req_Next_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resource_Req_Next_jButtonActionPerformed(evt);
            }
        });
        Resource_Req_Next_jButton.setBounds(110, 10, 100, 21);
        CustomisedReport_jDesktopPane4.add(Resource_Req_Next_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Resource_Req_Previous_jButton1.setText("< Previous");
        Resource_Req_Previous_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resource_Req_Previous_jButton1ActionPerformed(evt);
            }
        });
        Resource_Req_Previous_jButton1.setBounds(10, 10, 100, 21);
        CustomisedReport_jDesktopPane4.add(Resource_Req_Previous_jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CustomisedReport_jDesktopPane4.setBounds(20, 170, 730, 40);
        Planning_ProjectResource_Req_jDesktopPane1.add(CustomisedReport_jDesktopPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Resource_Req_Cost_jTextField.setBounds(650, 130, 100, 22);
        Planning_ProjectResource_Req_jDesktopPane1.add(Resource_Req_Cost_jTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Resource_Req_Cost_jLabel.setText("Cost");
        Resource_Req_Cost_jLabel.setBounds(600, 130, 50, 22);
        Planning_ProjectResource_Req_jDesktopPane1.add(Resource_Req_Cost_jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_ProjectResource_Req_jDesktopPane1.setBounds(20, 190, 760, 220);
        Project_Resources_jDesktopPane.add(Planning_ProjectResource_Req_jDesktopPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Project_Resources_jDesktopPane.setBounds(10, 0, 790, 470);
        Resource_jDesktopPane.add(Project_Resources_jDesktopPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Project_jTabbedPane.addTab("Project Resources", Resource_jDesktopPane);

        Constraint_jDesktopPane.setBackground(new java.awt.Color(255, 255, 204));
        Constraint_jDesktopPane.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Constraint_jDesktopPaneFocusGained(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Project Constraints"));
        jPanel4.setLayout(null);

        Reporting_Customised_jDesktopPane1.setBackground(new java.awt.Color(255, 255, 204));
        Reporting_Customised_jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Project Time Duration (Days)"));

        Reporting_Customised_jDesktopPane2.setBackground(new java.awt.Color(255, 255, 102));
        Reporting_Customised_jDesktopPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Project_Constraint_AvailableDuration_jLabel.setText("Total Duration");
        Project_Constraint_AvailableDuration_jLabel.setBounds(20, 30, 130, 25);
        Reporting_Customised_jDesktopPane2.add(Project_Constraint_AvailableDuration_jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Project_Constraint_ElapsedDuration_jLabel1.setText("Elapsed Time");
        Project_Constraint_ElapsedDuration_jLabel1.setBounds(20, 80, 130, 25);
        Reporting_Customised_jDesktopPane2.add(Project_Constraint_ElapsedDuration_jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Constraint_ElapsedTime_jTextField.setBounds(150, 80, 90, 25);
        Reporting_Customised_jDesktopPane2.add(Constraint_ElapsedTime_jTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Constraint_TotalDuration_jTextField.setBounds(150, 30, 90, 25);
        Reporting_Customised_jDesktopPane2.add(Constraint_TotalDuration_jTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Reporting_Customised_jDesktopPane2.setBounds(30, 50, 280, 140);
        Reporting_Customised_jDesktopPane1.add(Reporting_Customised_jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Reporting_Customised_jDesktopPane4.setBackground(new java.awt.Color(255, 255, 102));
        Reporting_Customised_jDesktopPane4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Constraint_RemainingTime_jTextField.setBounds(150, 20, 89, 25);
        Reporting_Customised_jDesktopPane4.add(Constraint_RemainingTime_jTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Project_Constraint_RemainingDuration_jLabel1.setText("Remaining Time");
        Project_Constraint_RemainingDuration_jLabel1.setBounds(20, 20, 130, 25);
        Reporting_Customised_jDesktopPane4.add(Project_Constraint_RemainingDuration_jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Reporting_Customised_jDesktopPane4.setBounds(30, 220, 280, 60);
        Reporting_Customised_jDesktopPane1.add(Reporting_Customised_jDesktopPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel4.add(Reporting_Customised_jDesktopPane1);
        Reporting_Customised_jDesktopPane1.setBounds(46, 31, 340, 310);

        Reporting_Customised_jDesktopPane3.setBackground(new java.awt.Color(255, 255, 204));
        Reporting_Customised_jDesktopPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Project Funds (Local Currency)"));

        Reporting_Customised_jDesktopPane5.setBackground(new java.awt.Color(255, 255, 102));
        Reporting_Customised_jDesktopPane5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Project_Constraint_AvailableFunds_jLabel.setText("Total Funds");
        Project_Constraint_AvailableFunds_jLabel.setBounds(20, 30, 120, 25);
        Reporting_Customised_jDesktopPane5.add(Project_Constraint_AvailableFunds_jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Constraint_TotalFunds_jTextField.setBounds(140, 30, 100, 25);
        Reporting_Customised_jDesktopPane5.add(Constraint_TotalFunds_jTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Project_Constraint_UsedFunds_jLabel.setText("Used Funds");
        Project_Constraint_UsedFunds_jLabel.setBounds(20, 80, 120, 25);
        Reporting_Customised_jDesktopPane5.add(Project_Constraint_UsedFunds_jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Constraint_UsedFunds_jTextField.setBounds(140, 80, 100, 25);
        Reporting_Customised_jDesktopPane5.add(Constraint_UsedFunds_jTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Reporting_Customised_jDesktopPane5.setBounds(30, 50, 280, 140);
        Reporting_Customised_jDesktopPane3.add(Reporting_Customised_jDesktopPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Reporting_Customised_jDesktopPane6.setBackground(new java.awt.Color(255, 255, 102));
        Reporting_Customised_jDesktopPane6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Project_Constraint_RemainingFunds_jLabel1.setText("Remaining Funds");
        Project_Constraint_RemainingFunds_jLabel1.setBounds(20, 20, 120, 20);
        Reporting_Customised_jDesktopPane6.add(Project_Constraint_RemainingFunds_jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Constraint_RemainingFunds_jTextField.setBounds(139, 20, 100, 25);
        Reporting_Customised_jDesktopPane6.add(Constraint_RemainingFunds_jTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Reporting_Customised_jDesktopPane6.setBounds(30, 220, 280, 60);
        Reporting_Customised_jDesktopPane3.add(Reporting_Customised_jDesktopPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel4.add(Reporting_Customised_jDesktopPane3);
        Reporting_Customised_jDesktopPane3.setBounds(410, 30, 340, 310);

        Reporting_Customised_jDesktopPane7.setBackground(new java.awt.Color(255, 255, 204));
        Reporting_Customised_jDesktopPane7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Reporting_Customised_jDesktopPane10.setBackground(new java.awt.Color(255, 255, 102));
        Reporting_Customised_jDesktopPane10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Constraint_Save_jButton.setText("Save");
        Constraint_Save_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Constraint_Save_jButtonActionPerformed(evt);
            }
        });
        Constraint_Save_jButton.setBounds(10, 10, 290, 30);
        Reporting_Customised_jDesktopPane10.add(Constraint_Save_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Constraint_Refresh_jButton.setText("Refresh");
        Constraint_Refresh_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Constraint_Refresh_jButtonActionPerformed(evt);
            }
        });
        Constraint_Refresh_jButton.setBounds(320, 10, 290, 30);
        Reporting_Customised_jDesktopPane10.add(Constraint_Refresh_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Reporting_Customised_jDesktopPane10.setBounds(30, 20, 640, 50);
        Reporting_Customised_jDesktopPane7.add(Reporting_Customised_jDesktopPane10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel4.add(Reporting_Customised_jDesktopPane7);
        Reporting_Customised_jDesktopPane7.setBounds(50, 370, 700, 90);

        jPanel4.setBounds(0, 0, 800, 490);
        Constraint_jDesktopPane.add(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Project_jTabbedPane.addTab("Project Constraints", Constraint_jDesktopPane);

        Project_jTabbedPane.setBounds(10, 10, 820, 510);
        Prerequisite_Source_jDesktopPane.add(Project_jTabbedPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu3.setText("File");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenu3.add(jSeparator3);

        Phase_Save_jMenuItem.setText("Save");
        Phase_Save_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phase_Save_jMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(Phase_Save_jMenuItem);

        Phase_SaveAs_jMenuItem.setText("Save As");
        Phase_SaveAs_jMenuItem.setToolTipText("");
        Phase_SaveAs_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phase_SaveAs_jMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(Phase_SaveAs_jMenuItem);
        jMenu3.add(jSeparator1);

        jMenuItem1.setText("Load");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);
        jMenu3.add(jSeparator2);

        menuBar.add(jMenu3);

        jMenu1.setText("Exit");

        Phase_Close_jMenuItem.setText("Close");
        Phase_Close_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phase_Close_jMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(Phase_Close_jMenuItem);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Prerequisite_Source_jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Prerequisite_Source_jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Resource_Add_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resource_Add_jButtonActionPerformed
        this.save_resource();
        this.clear_resource();
    }//GEN-LAST:event_Resource_Add_jButtonActionPerformed

    private void Resource_Save_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resource_Save_jButtonActionPerformed
        this.save_resource();
    }//GEN-LAST:event_Resource_Save_jButtonActionPerformed

    private void Resource_Refresh_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resource_Refresh_jButtonActionPerformed
        this.refresh_resource();
    }//GEN-LAST:event_Resource_Refresh_jButtonActionPerformed

    private void Constraint_Save_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Constraint_Save_jButtonActionPerformed
        this.save_constraint();
    }//GEN-LAST:event_Constraint_Save_jButtonActionPerformed

    private void Constraint_Refresh_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Constraint_Refresh_jButtonActionPerformed
        this.refresh_constraints();
    }//GEN-LAST:event_Constraint_Refresh_jButtonActionPerformed

    private void Resource_Req_Add_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resource_Req_Add_jButtonActionPerformed
        this.save_requirement();
        this.clear_requirement();
    }//GEN-LAST:event_Resource_Req_Add_jButtonActionPerformed

    private void Resource_Req_Save_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resource_Req_Save_jButtonActionPerformed
        this.save_requirement();
    }//GEN-LAST:event_Resource_Req_Save_jButtonActionPerformed

    private void Resource_Req_Refresh_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resource_Req_Refresh_jButtonActionPerformed
        this.refresh_requirement();
    }//GEN-LAST:event_Resource_Req_Refresh_jButtonActionPerformed

    private void Resource_Req_Previous_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resource_Req_Previous_jButton1ActionPerformed
    this.previous_requirement();
    }//GEN-LAST:event_Resource_Req_Previous_jButton1ActionPerformed

    private void Resource_Req_Next_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resource_Req_Next_jButtonActionPerformed
    this.next_requirement();
    }//GEN-LAST:event_Resource_Req_Next_jButtonActionPerformed

    private void Resource_Req__Delete_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resource_Req__Delete_jButtonActionPerformed
       this.delete_requirement();
    }//GEN-LAST:event_Resource_Req__Delete_jButtonActionPerformed

    private void Resource_First_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resource_First_jButtonActionPerformed
       this.first_resource();
    }//GEN-LAST:event_Resource_First_jButtonActionPerformed

    private void Resource_Previous_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resource_Previous_jButtonActionPerformed
        this.previous_resource();
    }//GEN-LAST:event_Resource_Previous_jButtonActionPerformed

    private void Resource_Next_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resource_Next_jButtonActionPerformed
        this.next_resource();
    }//GEN-LAST:event_Resource_Next_jButtonActionPerformed

    private void Resource_Last_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resource_Last_jButtonActionPerformed
        this.last_resource();
    }//GEN-LAST:event_Resource_Last_jButtonActionPerformed

    private void Resource_New_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resource_New_jButtonActionPerformed
        this.clear_resource();
    }//GEN-LAST:event_Resource_New_jButtonActionPerformed

    private void Resource_Delete_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resource_Delete_jButtonActionPerformed
        this.delete_resource();
    }//GEN-LAST:event_Resource_Delete_jButtonActionPerformed

    private void Resource_jDesktopPaneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Resource_jDesktopPaneFocusGained
        this.refresh_resource();

}//GEN-LAST:event_Resource_jDesktopPaneFocusGained

    private void Constraint_jDesktopPaneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Constraint_jDesktopPaneFocusGained
        this.refresh_constraints();
}//GEN-LAST:event_Constraint_jDesktopPaneFocusGained

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
   this.save_constraint();
   this.save_resource();

    }//GEN-LAST:event_formWindowClosed

    private void Phase_Save_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phase_Save_jMenuItemActionPerformed
        this.save_constraint();
        this.save_requirement();
        this.save_resource();
}//GEN-LAST:event_Phase_Save_jMenuItemActionPerformed

    private void Phase_SaveAs_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phase_SaveAs_jMenuItemActionPerformed
        if (Global.project !=null && Global.project.getSupplements()!=null &&
                Global.project.getSupplements().getManagement()!=null)
        {
            File selectedFile =Tools.chooseFile("Choose Location", null, Global.project.getLocation(), true);
            String selectedFileString = (selectedFile != null) ? selectedFile.getPath() : null;

            if (selectedFileString!=null)
                Global.project.getSupplements().getManagement().store(selectedFileString);
        }
}//GEN-LAST:event_Phase_SaveAs_jMenuItemActionPerformed

    private void Phase_Close_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phase_Close_jMenuItemActionPerformed
        this.save_constraint();
        this.save_requirement();
        this.save_resource();
        this.dispose();
}//GEN-LAST:event_Phase_Close_jMenuItemActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    if (Global.project!=null && Global.project.getSupplements()==null)
        Global.project.setSupplements(new Supplements());

    Management management= new Management().open();
    if (management!=null)
        Global.project.getSupplements().setManagement(management);

    //
    this.refresh_constraints();
    this.refresh_resource();
    //
    this.populate_resource();
    this.populate_constraint();
    //
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ManagementForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Constraint_ElapsedTime_jTextField;
    private javax.swing.JButton Constraint_Refresh_jButton;
    private javax.swing.JTextField Constraint_RemainingFunds_jTextField;
    private javax.swing.JTextField Constraint_RemainingTime_jTextField;
    private javax.swing.JButton Constraint_Save_jButton;
    private javax.swing.JTextField Constraint_TotalDuration_jTextField;
    private javax.swing.JTextField Constraint_TotalFunds_jTextField;
    private javax.swing.JTextField Constraint_UsedFunds_jTextField;
    private javax.swing.JDesktopPane Constraint_jDesktopPane;
    private javax.swing.JDesktopPane CustomisedReport_jDesktopPane1;
    private javax.swing.JDesktopPane CustomisedReport_jDesktopPane4;
    private javax.swing.JMenuItem Phase_Close_jMenuItem;
    private javax.swing.JMenuItem Phase_SaveAs_jMenuItem;
    private javax.swing.JMenuItem Phase_Save_jMenuItem;
    private javax.swing.JLabel Planning_ProjectResourceReqType_jLabel1;
    private javax.swing.JDesktopPane Planning_ProjectResource_Req_jDesktopPane1;
    private javax.swing.JLabel Planning_Project_Resource_Type_jLabel;
    private javax.swing.JDesktopPane Prerequisite_Source_jDesktopPane;
    private javax.swing.JLabel Project_Constraint_AvailableDuration_jLabel;
    private javax.swing.JLabel Project_Constraint_AvailableFunds_jLabel;
    private javax.swing.JLabel Project_Constraint_ElapsedDuration_jLabel1;
    private javax.swing.JLabel Project_Constraint_RemainingDuration_jLabel1;
    private javax.swing.JLabel Project_Constraint_RemainingFunds_jLabel1;
    private javax.swing.JLabel Project_Constraint_UsedFunds_jLabel;
    private javax.swing.JDesktopPane Project_Resources_jDesktopPane;
    private javax.swing.JTabbedPane Project_jTabbedPane;
    private javax.swing.JDesktopPane Reporting_Customised_jDesktopPane1;
    private javax.swing.JDesktopPane Reporting_Customised_jDesktopPane10;
    private javax.swing.JDesktopPane Reporting_Customised_jDesktopPane2;
    private javax.swing.JDesktopPane Reporting_Customised_jDesktopPane3;
    private javax.swing.JDesktopPane Reporting_Customised_jDesktopPane4;
    private javax.swing.JDesktopPane Reporting_Customised_jDesktopPane5;
    private javax.swing.JDesktopPane Reporting_Customised_jDesktopPane6;
    private javax.swing.JDesktopPane Reporting_Customised_jDesktopPane7;
    private javax.swing.JButton Resource_Add_jButton;
    private javax.swing.JLabel Resource_Cost_jLabel;
    private javax.swing.JTextField Resource_Cost_jTextField;
    private javax.swing.JButton Resource_Delete_jButton;
    private javax.swing.JTextArea Resource_Description_jTextArea;
    private javax.swing.JButton Resource_First_jButton;
    private javax.swing.JButton Resource_Last_jButton;
    private javax.swing.JButton Resource_New_jButton;
    private javax.swing.JButton Resource_Next_jButton;
    private javax.swing.JButton Resource_Previous_jButton;
    private javax.swing.JButton Resource_Refresh_jButton;
    private javax.swing.JButton Resource_Req_Add_jButton;
    private javax.swing.JLabel Resource_Req_Cost_jLabel;
    private javax.swing.JTextField Resource_Req_Cost_jTextField;
    private javax.swing.JTextArea Resource_Req_Description_jTextArea;
    private javax.swing.JButton Resource_Req_Next_jButton;
    private javax.swing.JButton Resource_Req_Previous_jButton1;
    private javax.swing.JButton Resource_Req_Refresh_jButton;
    private javax.swing.JButton Resource_Req_Save_jButton;
    private javax.swing.JComboBox Resource_Req_Type_jComboBox;
    private javax.swing.JButton Resource_Req__Delete_jButton;
    private javax.swing.JButton Resource_Save_jButton;
    private javax.swing.JComboBox Resource_Type_jComboBox;
    private javax.swing.JDesktopPane Resource_jDesktopPane;
    private javax.swing.JDesktopPane jDesktopPane26;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
//****************************************************************************
//                              Save Resource
//****************************************************************************
//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

 private void save_constraint()
 {
   try
     {
    if (this.constraint==null)
        this.constraint=new Constraints();
     //
     if(this.Constraint_TotalDuration_jTextField.getText()!=null
     && !this.Constraint_TotalDuration_jTextField.getText().equals(""))
             this.constraint.setTotalDuration(Double.parseDouble(this.Constraint_TotalDuration_jTextField.getText()));
     //
     if(this.Constraint_ElapsedTime_jTextField.getText()!=null
     && !this.Constraint_ElapsedTime_jTextField.getText().equals(""))
             this.constraint.setElapsedTime(Double.parseDouble(this.Constraint_ElapsedTime_jTextField.getText()));
    //
     if(this.Constraint_TotalFunds_jTextField.getText()!=null
     && !this.Constraint_TotalFunds_jTextField.getText().equals(""))
        this.constraint.setTotalFunds(Double.parseDouble(this.Constraint_TotalFunds_jTextField.getText()));

     if(this.Constraint_UsedFunds_jTextField.getText()!=null
     && !this.Constraint_UsedFunds_jTextField.getText().equals(""))
        this.constraint.setUsedFunds(Double.parseDouble(this.Constraint_UsedFunds_jTextField.getText()));

      Global.project.getSupplements().getManagement().setConstraint(constraint);

      Global.project.getSupplements().getManagement().store(null);

     } catch (Exception ex) {
            Logger.getLogger(ManagementForm.class.getName()).log(Level.SEVERE, null, ex);
     }
  }

 //RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
 //                         Refresh Constraints
 //RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
 private void refresh_constraints()
 {
{
    if (Global.project!=null &&
        Global.project.getSupplements().getManagement()!=null&&
        Global.project.getSupplements().getManagement().getConstraint()!=null
        )
    {
        this.constraint=Global.project.getSupplements().getManagement().getConstraint();
        this.populate_constraint();
    }
    //else
        //System.out.print(" No Resource is available");
}
}

//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
//                         Populate Resource Form
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
 private void populate_constraint()
{
     if (this.constraint!=null)
     {
         this.Constraint_TotalDuration_jTextField.setText(String.valueOf(constraint.getTotalDuration()));
         this.Constraint_TotalFunds_jTextField.setText(String.valueOf(constraint.getTotalFunds()));
         this.Constraint_ElapsedTime_jTextField.setText(String.valueOf(constraint.getElapsedTime()));
         this.Constraint_UsedFunds_jTextField.setText(String.valueOf(constraint.getUsedFunds()));
         //
         this.Constraint_RemainingFunds_jTextField.setText(String.valueOf(constraint.getRemainingFunds()));
         this.Constraint_RemainingTime_jTextField.setText(String.valueOf(constraint.getRemainingTime()));

     }
    else
      //System.out.print(" No Constraints found to populate");
     this.populateForm();
 }


 //SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
//****************************************************************************
//                              Save Resource
//****************************************************************************
//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

 private void save_resource()
 {
   try
     {
    if (this.resource==null)
        this.resource=new Resource();
     //
     if(this.Resource_Description_jTextArea.getText()!=null
     && !this.Resource_Description_jTextArea.getText().equals(""))
        this.resource.setDescription(this.Resource_Description_jTextArea.getText());
     //
     if(this.Resource_Cost_jTextField.getText()!=null
     && !this.Resource_Cost_jTextField.getText().equals(""))
        this.resource.setCost(Double.parseDouble(this.Resource_Cost_jTextField.getText()));
     //     
    if (this.Resource_Type_jComboBox.getSelectedIndex()>0)
         this.resource.setResourceTypeIndex(this.Resource_Type_jComboBox.getSelectedIndex());

     Global.project.getSupplements().getManagement().getResources().save(resource);

     Global.project.getSupplements().getManagement().store(null);

     } catch (Exception ex) {
            Logger.getLogger(ManagementForm.class.getName()).log(Level.SEVERE, null, ex);
     }
   this.save_requirement();
  }

 //RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
//****************************************************************************
//                              Refresh Resource
//****************************************************************************
//RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR

 private void refresh_resource()
 {
    if (Global.project!=null &&
        Global.project.getSupplements()!=null &&
        Global.project.getSupplements().getManagement()!=null &&
        Global.project.getSupplements().getManagement().getResources()!=null &&
        Global.project.getSupplements().getManagement().getResources().getResourcesList().size()>0
        )
    {
        if (Global.project.getSupplements().getManagement().getResources().getFirst()!=null)
             this.resource = Global.project.getSupplements().getManagement().getResources().getFirst();
        this.populate_resource();
    }

    this.refresh_requirement();
}


//DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
//****************************************************************************
//                              Delete Resource
//DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
//****************************************************************************
 private void delete_resource()
    {
    int index= Global.project.getSupplements().getManagement().getResources().getResourcesList().indexOf(this.resource);
    if (this.resource!=null && Global.project.getSupplements().getManagement().getResources()!=null)
        if (Global.project.getSupplements().getManagement().getResources().delete(this.resource)==0);
        {
            if (Global.project.getSupplements().getManagement().getResources().getResourcesList().size()>0)
            {
                if (index==0)
                    this.resource = Global.project.getSupplements().getManagement().getResources().getResource(index);
                else
                    this.resource = Global.project.getSupplements().getManagement().getResources().getResource(index-1);
                this.refresh_requirement();
                this.populate_resource();
            }
            else
            this.clear_resource();
        }

     this.save_resource();
     
 }



/*
 //DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
//****************************************************************************
//                              Delete Requirement
//DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
//****************************************************************************
 private void delete_requirement()
    {
    if (this.resource!=null && this.resource.getRequirements()!=null
            && this.resource.getRequirements().getRequirementsList().size()>0)
    {
        int index= this.resource.getRequirements().getRequirementsList().indexOf(this.requirement);
        if (this.resource.getRequirements().delete(this.requirement)==0);
        {
            if (this.resource.getRequirements().getRequirementsList().size()>0)
            {
                if (index==0)
                    this.resource = this.resource.getRequirements().getRequirement(index);
                else
                    this.resource = this.resource.getRequirements().getRequirement(index-1);

                this.populate_requirement();
            }
            else
            this.clear_requirement();
        }

     this.save_requirement();
     }
 }

*/

 //DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
//****************************************************************************
//                              Delete Requirement
//DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
//****************************************************************************
 private void delete_requirement()
   {
    if (this.requirement!=null && this.resource!=null  &&
        this.resource.getRequirements()!=null )
    {
        int index= this.resource.getRequirements().getRequirementsList().indexOf(this.requirement);
        if (this.resource.getRequirements().delete(this.requirement)==0);
        {
            if (this.resource.getRequirements().getRequirementsList().size()>0)
            {
                if (index==0)
                    this.requirement = this.resource.getRequirements().getRequirement(index);
                else
                    this.requirement = this.resource.getRequirements().getRequirement(index-1);

                this.populate_requirement();
            }
            else
            this.clear_requirement();
        }

     this.save_requirement();
 }
}




 /*
//DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
//****************************************************************************
//                              Delete Plan
//DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
//****************************************************************************
 private void delete_plan()
    {
    if (this.plan!=null && this.phase.getPlanning()!=null)
    {
      int index= this.phase.getPlanning().getPlanList().indexOf(this.plan);
          if (this.phase.getPlanning().delete(this.plan));
        {
            if (this.phase.getPlanning().getPlanList().size()>0)
            {
                if (index==0 && this.phase.getPlanning().getPlan(index)!=null)
                    this.plan = this.phase.getPlanning().getPlan(index);
                else
                    this.plan = this.phase.getPlanning().getPlan(index-1);

                this.refresh_plan_details();
                this.populate_plan();
            }
            else
                this.clear_plan();
        }
     this.phase.save();
     //------------------------------------------------------------------------
     // to disable the details if the master is not there
     //------------------------------------------------------------------------
     if (this.phase.getPlanning().getPlanList().size()==0)
     {
         this.phase.setPlanning(null);
         this.populateForm();
      }
 }
 }

 */







//CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
//****************************************************************************
//                     Clear Source Resource & Source
//****************************************************************************
 //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

 private void clear_resourceForm()
{
     this.Resource_Cost_jTextField.setText("");
     this.Resource_Description_jTextArea.setText("");
     this.Resource_Type_jComboBox.setSelectedIndex(0);
     this.clear_requirementForm();
 }

 //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 //                         Clear Resource Form
 //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
private void clear_constraintForm()
{
     this.Constraint_TotalDuration_jTextField.setText("");
     this.Constraint_TotalFunds_jTextField.setText("");
     this.Constraint_RemainingTime_jTextField.setText("");
     this.Constraint_ElapsedTime_jTextField.setText("");
     this.Constraint_UsedFunds_jTextField.setText("");
     this.Constraint_RemainingFunds_jTextField.setText("");
 }

 //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 //                              Clear resource
 //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 private void clear_resource( )
{
     this.clear_resourceForm();
     this.clear_requirement();
     this.resource=null;
 }

//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
//****************************************************************************
//                             Populate
//****************************************************************************
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP

private void populateForm()
{
    this.repaint();
    this.pack();
}

//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
//                         Populate Resource Form
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
 private void populate_resource()
{
     if (resource!=null)
     {
         if (resource.getDescription()!=null)
            this.Resource_Description_jTextArea.setText(resource.getDescription());
         else
           this.Resource_Description_jTextArea.setText("");
         //
         if (resource.getResourceType()!=null)
            this.Resource_Type_jComboBox.setSelectedIndex(resource.getResourceType().ordinal()+1);
         else
             this.Resource_Type_jComboBox.setSelectedIndex(0);

         this.Resource_Cost_jTextField.setText(String.valueOf(resource.getCost()));
         //
         this.populate_requirement();
     }
    //else
    //  //System.out.print(" No Resource found to populate");
     this.populateForm();
 }

//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
//****************************************************************************
//                              Save Requirement
//****************************************************************************
//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

 private void save_requirement()
{

if (!this.Resource_Req_Description_jTextArea.getText().equals(""))
{
     if (this.requirement==null)
        this.requirement=new Resource();
     //
     if(this.Resource_Req_Description_jTextArea.getText()!=null
     && !this.Resource_Req_Description_jTextArea.getText().equals(""))
        this.requirement.setDescription(this.Resource_Req_Description_jTextArea.getText());
     //
     if(this.Resource_Req_Cost_jTextField.getText()!=null
     && !this.Resource_Req_Cost_jTextField.getText().equals(""))
        this.requirement.setCost(Double.parseDouble(this.Resource_Req_Cost_jTextField.getText()));
     //

     if (this.Resource_Req_Type_jComboBox.getSelectedIndex()>0)
         this.requirement.setResourceTypeIndex(this.Resource_Req_Type_jComboBox.getSelectedIndex());
    //-------------------------------------------------------------------------
    if (this.resource==null)
        this.save_resource();

     if (this.resource!=null && this.resource.getRequirements()==null)
         this.resource.setRequirements(new Requirements());
     //

     if (this.resource!=null && this.resource.getRequirements()!=null &&  requirement!=null)
            this.resource.getRequirements().save(requirement);
     
     Global.project.getSupplements().getManagement().getResources().save(resource);
}
 //---------------------------------------------------------------------------- //System.out.print("SSSSSSSSSSSSSSSSS< saved source successfully >SSSSSSSSSSSSSSSSSS");
}

 //RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
 //                         Refresh Requirements
 //RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
 private void refresh_requirement()
 {
   this.clear_requirement();
    if (this.resource!=null)
    {
        if (this.resource.getRequirements() !=null)
        {
           if (this.resource.getRequirements().getRequirementsList().size()>0)
               this.requirement=this.resource.getRequirements().getFirst();
               this.populate_requirement();
        }
        //else
       //     //System.out.print(" No requirement is available yet");
   }
   //else
   // //System.out.print(" No Requirement is available yet");
}



//NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
//                          Next Source
//NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 private void next_requirement()
    {
       if(this.resource!=null&&this.resource.getRequirements()!=null)
           {
              Resource nReq=this.resource.getRequirements().getNext(this.requirement);
              if (nReq!=null)
              {
               this.save_requirement();
               this.requirement=nReq;
               this.populate_requirement();
              }
          }
      //  else
      //      //System.out.print("No PreRequisits Source is found yet ");
  }


 //PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
 //                           Previous Source
 //PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
 private void previous_requirement()
   {
       if(this.resource!=null&&this.resource.getRequirements()!=null)
           {
              Resource pReq=this.resource.getRequirements().getPrevious(this.requirement);
              if (pReq!=null)
              {
               this.save_requirement();
               this.requirement=pReq;
               this.populate_requirement();
              }
          }
      //  else
      //      //System.out.print("No PreRequisits Source is found yet ");
  }

//CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 //                              Clear Requirement
 //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 private void clear_requirement( )
{
     this.clear_requirementForm();
     this.requirement=null;
 }


 //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 //                         Clear Requirement Form
 //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
  private void clear_requirementForm()
{
     this.Resource_Req_Cost_jTextField.setText("");
     this.Resource_Req_Description_jTextArea.setText("");
     this.Resource_Req_Type_jComboBox.setSelectedIndex(0);
 }

 //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 //                              Clear Source
 //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 private void clear_constraint( )
{
     this.clear_constraintForm();
     this.constraint=null;
 }
 
//FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
//****************************************************************************
//                            First & Last Resource
//****************************************************************************
//FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

 private void first_resource()
  {
     if (Global.project.getSupplements().getManagement().getResources()!=null)
     {
         save_resource();
         this.resource=Global.project.getSupplements().getManagement().getResources().getFirst();
         this.refresh_requirement();
         this.populate_resource();
     }
 }

 //****************************************************************************
 private void last_resource()
  {
     if (Global.project.getSupplements().getManagement().getResources()!=null)
     {
         save_resource();
         this.resource=Global.project.getSupplements().getManagement().getResources().getLast();
         this.refresh_requirement();
         this.populate_resource();
      }
  }

//NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
//****************************************************************************
//                     Next Resource & Source
//****************************************************************************
//NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 private void next_resource()
    {
      if(Global.project.getSupplements().getManagement().getResources()!=null)
        {
            if (this.resource!=null)
            {
                if (Global.project.getSupplements().getManagement().getResources().getNext(this.resource)!=null)
                {
                    this.save_resource();
                    this.resource=Global.project.getSupplements().getManagement().getResources().getNext(this.resource);                    
                    this.refresh_requirement();
                    this.populate_resource();
                }
            }
        }     
    }

//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
//****************************************************************************
//                     Previous Resource& Source
//****************************************************************************
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
 private void previous_resource()
    {
      if(Global.project.getSupplements().getManagement().getResources()!=null)
        {
            if (this.resource!=null)
            {
                if (Global.project.getSupplements().getManagement().getResources().getPrevious(this.resource)!=null)
                {
                    this.save_resource();
                    this.resource=Global.project.getSupplements().getManagement().getResources().getPrevious(this.resource);
                    this.refresh_requirement();
                    this.populate_resource();
                }
            }
        }
       // else
       //     //System.out.print("No Phase PreRequisits is found yet ");
    }

 //PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
//                         Populate Requirement Form
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
 private void populate_requirement()
 {
     this.clear_requirementForm();
     //
     if (this.requirement!=null)
     {
         if (requirement.getDescription()!=null)
            this.Resource_Req_Description_jTextArea.setText(requirement.getDescription());
         else
           this.Resource_Req_Description_jTextArea.setText("");
         //
         if (requirement.getResourceType()!=null)
            this.Resource_Req_Type_jComboBox.setSelectedIndex(requirement.getResourceType().ordinal()+1);
         else
             this.Resource_Req_Type_jComboBox.setSelectedIndex(0);
        
         this.Resource_Req_Cost_jTextField.setText(String.valueOf(requirement.getCost()));
      }
     // else
     //    //System.out.print(" No Requirement found to populate");
     //
    this.populateForm();
 }
}
