/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QualityForm.java
 *
 * Created on 21-Oct-2010, 13:48:50
 */

package gui.form.supplement;
import java.io.File;

import javax.swing.DefaultComboBoxModel;

import toolbox.Tools;
import java.util.logging.Level;
import java.util.logging.Logger;
import process_model.supplement.Supplements;
import process_model.supplement.quality.Quality;
import global.Global;
import java.net.MalformedURLException;
import java.net.URL;
import process_model.supplement.quality.QualitySpecification;

/**
 *
 * @author amb04
 */
public class QualityForm extends javax.swing.JFrame {
  private QualitySpecification qualitySpecification=null;
  private String qualityDomainTypeArray[]={"",
                                        "Data Quality Assurance Policy",
                                        "Procedural Quality Assurance Policy",
                                        "Reporting Quality Assurance Policy ",
                                        "Other"};

  private String qualityTypeArray[]={"","Functional ",
                                        "Non-Functional",
                                        "Other"};
    /** Creates new form QualityForm */
  
  //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    public QualityForm() {
        initComponents();
        this.setTitle("Human Interaction Form");
        
         if (Global.project.getSupplements()==null)
            Global.project.setSupplements(new Supplements());

        if (Global.project.getSupplements().getQuality()==null)
            Global.project.getSupplements().setQuality(new Quality());

        if (this.qualitySpecification==null)
            this.refresh_quality();

        this.populate_quality();
        this.populateForm();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reporting_Customised_jDesktopPane3 = new javax.swing.JDesktopPane();
        CustomisedReport_jDesktopPane3 = new javax.swing.JDesktopPane();
        Add_jButton = new javax.swing.JButton();
        Delete_jButton = new javax.swing.JButton();
        Save_jButton = new javax.swing.JButton();
        New_jButton = new javax.swing.JButton();
        Refresh_jButton = new javax.swing.JButton();
        Last_jButton = new javax.swing.JButton();
        Next_jButton = new javax.swing.JButton();
        Previous_jButton = new javax.swing.JButton();
        First_jButton = new javax.swing.JButton();
        Load_jButton = new javax.swing.JButton();
        Planning_Planner_info_jDesktopPane = new javax.swing.JDesktopPane();
        URL_jLabel = new javax.swing.JLabel();
        Description_jLabel = new javax.swing.JLabel();
        jScrollPane62 = new javax.swing.JScrollPane();
        Description_jTextArea = new javax.swing.JTextArea();
        Type_jComboBox = new javax.swing.JComboBox();
        Type_jLabel = new javax.swing.JLabel();
        URL_jTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Release_jLabel = new javax.swing.JLabel();
        Release_jTextField = new javax.swing.JTextField();
        Domain_jLabel = new javax.swing.JLabel();
        Domain_jComboBox = new javax.swing.JComboBox();
        menuBar = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Phase_Save_jMenuItem = new javax.swing.JMenuItem();
        Phase_SaveAs_jMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Phase_Load_jMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        Phase_Close_jMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quality Form");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Reporting_Customised_jDesktopPane3.setBackground(new java.awt.Color(255, 255, 204));
        Reporting_Customised_jDesktopPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Reporting_Customised_jDesktopPane3.setName("Reporting_Customised_jDesktopPane3"); // NOI18N

        CustomisedReport_jDesktopPane3.setBackground(new java.awt.Color(255, 255, 153));
        CustomisedReport_jDesktopPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CustomisedReport_jDesktopPane3.setName("CustomisedReport_jDesktopPane3"); // NOI18N

        Add_jButton.setText("Add +");
        Add_jButton.setName("Add_jButton"); // NOI18N
        Add_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_jButtonActionPerformed(evt);
            }
        });
        Add_jButton.setBounds(240, 40, 110, 25);
        CustomisedReport_jDesktopPane3.add(Add_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Delete_jButton.setText("Delete");
        Delete_jButton.setName("Delete_jButton"); // NOI18N
        Delete_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_jButtonActionPerformed(evt);
            }
        });
        Delete_jButton.setBounds(350, 40, 110, 25);
        CustomisedReport_jDesktopPane3.add(Delete_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Save_jButton.setText("Save");
        Save_jButton.setName("Save_jButton"); // NOI18N
        Save_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_jButtonActionPerformed(evt);
            }
        });
        Save_jButton.setBounds(120, 40, 120, 25);
        CustomisedReport_jDesktopPane3.add(Save_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        New_jButton.setText("New");
        New_jButton.setName("New_jButton"); // NOI18N
        New_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_jButtonActionPerformed(evt);
            }
        });
        New_jButton.setBounds(10, 40, 110, 25);
        CustomisedReport_jDesktopPane3.add(New_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Refresh_jButton.setText("Refresh");
        Refresh_jButton.setName("Refresh_jButton"); // NOI18N
        Refresh_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_jButtonActionPerformed(evt);
            }
        });
        Refresh_jButton.setBounds(460, 40, 110, 25);
        CustomisedReport_jDesktopPane3.add(Refresh_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Last_jButton.setText("Last >>");
        Last_jButton.setName("Last_jButton"); // NOI18N
        Last_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Last_jButtonActionPerformed(evt);
            }
        });
        Last_jButton.setBounds(350, 10, 110, 25);
        CustomisedReport_jDesktopPane3.add(Last_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Next_jButton.setText("Next >");
        Next_jButton.setName("Next_jButton"); // NOI18N
        Next_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_jButtonActionPerformed(evt);
            }
        });
        Next_jButton.setBounds(240, 10, 110, 25);
        CustomisedReport_jDesktopPane3.add(Next_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Previous_jButton.setText("< Previous");
        Previous_jButton.setName("Previous_jButton"); // NOI18N
        Previous_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Previous_jButtonActionPerformed(evt);
            }
        });
        Previous_jButton.setBounds(120, 10, 120, 25);
        CustomisedReport_jDesktopPane3.add(Previous_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        First_jButton.setText("<< First");
        First_jButton.setName("First_jButton"); // NOI18N
        First_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                First_jButtonActionPerformed(evt);
            }
        });
        First_jButton.setBounds(10, 10, 110, 25);
        CustomisedReport_jDesktopPane3.add(First_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Load_jButton.setText("Load");
        Load_jButton.setName("Load_jButton"); // NOI18N
        Load_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Load_jButtonActionPerformed(evt);
            }
        });
        Load_jButton.setBounds(460, 10, 110, 25);
        CustomisedReport_jDesktopPane3.add(Load_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CustomisedReport_jDesktopPane3.setBounds(20, 390, 580, 80);
        Reporting_Customised_jDesktopPane3.add(CustomisedReport_jDesktopPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_info_jDesktopPane.setBackground(new java.awt.Color(255, 255, 153));
        Planning_Planner_info_jDesktopPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Planning_Planner_info_jDesktopPane.setName("Planning_Planner_info_jDesktopPane"); // NOI18N

        URL_jLabel.setText("Quality Policy URL");
        URL_jLabel.setName("URL_jLabel"); // NOI18N
        URL_jLabel.setBounds(20, 220, 450, 20);
        Planning_Planner_info_jDesktopPane.add(URL_jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Description_jLabel.setText("Quality Assurance Description");
        Description_jLabel.setName("Description_jLabel"); // NOI18N
        Description_jLabel.setBounds(20, 20, 540, 20);
        Planning_Planner_info_jDesktopPane.add(Description_jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane62.setName("jScrollPane62"); // NOI18N

        Description_jTextArea.setColumns(20);
        Description_jTextArea.setRows(5);
        Description_jTextArea.setName("Description_jTextArea"); // NOI18N
        jScrollPane62.setViewportView(Description_jTextArea);

        jScrollPane62.setBounds(20, 40, 540, 90);
        Planning_Planner_info_jDesktopPane.add(jScrollPane62, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Type_jComboBox.setModel(new DefaultComboBoxModel(this.qualityTypeArray));
        Type_jComboBox.setName("Type_jComboBox"); // NOI18N
        Type_jComboBox.setBounds(20, 310, 180, 25);
        Planning_Planner_info_jDesktopPane.add(Type_jComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Type_jLabel.setText("Quality Type");
        Type_jLabel.setName("Type_jLabel"); // NOI18N
        Type_jLabel.setBounds(20, 290, 180, 20);
        Planning_Planner_info_jDesktopPane.add(Type_jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        URL_jTextField.setName("URL_jTextField"); // NOI18N
        URL_jTextField.setBounds(20, 240, 440, 25);
        Planning_Planner_info_jDesktopPane.add(URL_jTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Browse");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(460, 240, 100, 25);
        Planning_Planner_info_jDesktopPane.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Release_jLabel.setText("Quality Policy Version");
        Release_jLabel.setName("Release_jLabel"); // NOI18N
        Release_jLabel.setBounds(20, 150, 280, 20);
        Planning_Planner_info_jDesktopPane.add(Release_jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Release_jTextField.setName("Release_jTextField"); // NOI18N
        Release_jTextField.setBounds(20, 170, 280, 25);
        Planning_Planner_info_jDesktopPane.add(Release_jTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Domain_jLabel.setText("Quality  Policy Domain");
        Domain_jLabel.setName("Domain_jLabel"); // NOI18N
        Domain_jLabel.setBounds(290, 290, 270, 20);
        Planning_Planner_info_jDesktopPane.add(Domain_jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Domain_jComboBox.setModel(new DefaultComboBoxModel(this.qualityDomainTypeArray));
        Domain_jComboBox.setName("Domain_jComboBox"); // NOI18N
        Domain_jComboBox.setBounds(290, 310, 270, 25);
        Planning_Planner_info_jDesktopPane.add(Domain_jComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_info_jDesktopPane.setBounds(20, 20, 580, 350);
        Reporting_Customised_jDesktopPane3.add(Planning_Planner_info_jDesktopPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu3.setText("File");
        jMenu3.setName("jMenu3"); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jSeparator3.setName("jSeparator3"); // NOI18N
        jMenu3.add(jSeparator3);

        Phase_Save_jMenuItem.setText("Save");
        Phase_Save_jMenuItem.setName("Phase_Save_jMenuItem"); // NOI18N
        Phase_Save_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phase_Save_jMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(Phase_Save_jMenuItem);

        Phase_SaveAs_jMenuItem.setText("Sava As");
        Phase_SaveAs_jMenuItem.setName("Phase_SaveAs_jMenuItem"); // NOI18N
        Phase_SaveAs_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phase_SaveAs_jMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(Phase_SaveAs_jMenuItem);

        jSeparator1.setName("jSeparator1"); // NOI18N
        jMenu3.add(jSeparator1);

        Phase_Load_jMenuItem.setText("Load ");
        Phase_Load_jMenuItem.setName("Phase_Load_jMenuItem"); // NOI18N
        Phase_Load_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phase_Load_jMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(Phase_Load_jMenuItem);

        jSeparator2.setName("jSeparator2"); // NOI18N
        jMenu3.add(jSeparator2);

        menuBar.add(jMenu3);

        jMenu1.setText("Exit");
        jMenu1.setName("jMenu1"); // NOI18N

        Phase_Close_jMenuItem.setText("Close");
        Phase_Close_jMenuItem.setName("Phase_Close_jMenuItem"); // NOI18N
        Phase_Close_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phase_Close_jMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(Phase_Close_jMenuItem);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Reporting_Customised_jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Reporting_Customised_jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_jButtonActionPerformed
        this.save_quality();
        this.clear_quality();
}//GEN-LAST:event_Add_jButtonActionPerformed

    private void Delete_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_jButtonActionPerformed
        this.delete_quality();
}//GEN-LAST:event_Delete_jButtonActionPerformed

    private void Save_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_jButtonActionPerformed
        this.save_quality();
}//GEN-LAST:event_Save_jButtonActionPerformed

    private void New_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_jButtonActionPerformed
        this.clear_quality();
}//GEN-LAST:event_New_jButtonActionPerformed

    private void Refresh_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_jButtonActionPerformed
        this.refresh_quality();
}//GEN-LAST:event_Refresh_jButtonActionPerformed

    private void Last_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Last_jButtonActionPerformed
        this.last_quality();
}//GEN-LAST:event_Last_jButtonActionPerformed

    private void Next_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_jButtonActionPerformed
        this.next_quality();
}//GEN-LAST:event_Next_jButtonActionPerformed

    private void Previous_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Previous_jButtonActionPerformed
        this.previous_quality();
}//GEN-LAST:event_Previous_jButtonActionPerformed

    private void First_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_First_jButtonActionPerformed
        this.first_quality();
}//GEN-LAST:event_First_jButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //CustomFileFilter fileFilter = new CustomFileFilter("doc", "Quality Specification" + "File  *.doc");
        //File path = Tools.chooseFile("Select Quality Specification Document", fileFilter, null, false);
        File path = Tools.chooseFile("Select Quality Specification Document", null, null, false);

        if (path != null)
            this.URL_jTextField.setText("file:/"+path.getAbsolutePath());
        else
            this.URL_jTextField.setText(null);

        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void Load_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Load_jButtonActionPerformed

    if (Global.project!=null && Global.project.getSupplements()==null)
        Global.project.setSupplements(new Supplements());
    //
    Quality quality= new Quality().open();
    if (quality!=null)
        Global.project.getSupplements().setQuality(quality);
    //
    this.refresh_quality();
    //
    this.populate_quality();
    //
}//GEN-LAST:event_Load_jButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    this.save_quality();
    }//GEN-LAST:event_formWindowClosed

    private void Phase_Load_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phase_Load_jMenuItemActionPerformed

    this.Load_jButtonActionPerformed(evt);
}//GEN-LAST:event_Phase_Load_jMenuItemActionPerformed

    private void Phase_Save_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phase_Save_jMenuItemActionPerformed
        this.save_quality();
}//GEN-LAST:event_Phase_Save_jMenuItemActionPerformed

    private void Phase_SaveAs_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phase_SaveAs_jMenuItemActionPerformed
        if (Global.project !=null && Global.project.getSupplements()!=null &&
                Global.project.getSupplements().getQuality()!=null) {
            File selectedFile =Tools.chooseFile("Choose Location", null, Global.project.getLocation(), true);
            String selectedFileString = (selectedFile != null) ? selectedFile.getPath() : null;

            if (selectedFileString!=null)
                Global.project.getSupplements().getQuality().store(selectedFileString);
        }
}//GEN-LAST:event_Phase_SaveAs_jMenuItemActionPerformed

    private void Phase_Close_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phase_Close_jMenuItemActionPerformed
        this.Save_jButtonActionPerformed(evt);
        this.dispose();
}//GEN-LAST:event_Phase_Close_jMenuItemActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jMenu3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new QualityForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_jButton;
    private javax.swing.JDesktopPane CustomisedReport_jDesktopPane3;
    private javax.swing.JButton Delete_jButton;
    private javax.swing.JLabel Description_jLabel;
    private javax.swing.JTextArea Description_jTextArea;
    private javax.swing.JComboBox Domain_jComboBox;
    private javax.swing.JLabel Domain_jLabel;
    private javax.swing.JButton First_jButton;
    private javax.swing.JButton Last_jButton;
    private javax.swing.JButton Load_jButton;
    private javax.swing.JButton New_jButton;
    private javax.swing.JButton Next_jButton;
    private javax.swing.JMenuItem Phase_Close_jMenuItem;
    private javax.swing.JMenuItem Phase_Load_jMenuItem;
    private javax.swing.JMenuItem Phase_SaveAs_jMenuItem;
    private javax.swing.JMenuItem Phase_Save_jMenuItem;
    private javax.swing.JDesktopPane Planning_Planner_info_jDesktopPane;
    private javax.swing.JButton Previous_jButton;
    private javax.swing.JButton Refresh_jButton;
    private javax.swing.JLabel Release_jLabel;
    private javax.swing.JTextField Release_jTextField;
    private javax.swing.JDesktopPane Reporting_Customised_jDesktopPane3;
    private javax.swing.JButton Save_jButton;
    private javax.swing.JComboBox Type_jComboBox;
    private javax.swing.JLabel Type_jLabel;
    private javax.swing.JLabel URL_jLabel;
    private javax.swing.JTextField URL_jTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JScrollPane jScrollPane62;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables




//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
//****************************************************************************
//                              Save Resource
//****************************************************************************
//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

 private void save_quality()
 {
 try
   {
    if (this.qualitySpecification==null)
        this.qualitySpecification=new QualitySpecification();
     //
     try{
        if(this.URL_jTextField!=null && !this.URL_jTextField.getText().equals(""))
            this.qualitySpecification.setSpecificationURL(new URL(this.URL_jTextField.getText()));
        } catch (MalformedURLException x) {
              Logger.getLogger(QualityForm.class.getName()).log(Level.SEVERE, null, x);
         }

     if(this.Description_jTextArea!=null &&
       !this.Description_jTextArea.getText().equals(""))
        {
           this.qualitySpecification.setDescription(this.Description_jTextArea.getText());
        }

    if(this.Release_jTextField!=null && !this.Release_jTextField.getText().equals(""))
        this.qualitySpecification.setRelease(this.Release_jTextField.getText());

    //
     this.qualitySpecification.setDomainType(this.Domain_jComboBox.getSelectedIndex());
     this.qualitySpecification.setQualityType(this.Type_jComboBox.getSelectedIndex());
    //

     Global.project.getSupplements().getQuality().save(qualitySpecification);
     Global.project.getSupplements().getQuality().store(null);
         
   } catch (Exception ex) {
     Logger.getLogger(QualityForm.class.getName()).log(Level.SEVERE, null, ex);
  }
}



 //RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
//****************************************************************************
//                              Refresh
//****************************************************************************
//RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR

 private void refresh_quality()
 {
    if (Global.project!=null &&
        Global.project.getSupplements().getQuality()!=null&&
        Global.project.getSupplements().getQuality()!=null &&
        Global.project.getSupplements().getQuality().getSpecificationsList().size()>0
        )
    {
        this.qualitySpecification = Global.project.getSupplements().getQuality().getFirst();
        this.populate_quality();
    }
    //else
        //System.out.print(" No Resource is available");
}


//DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
//****************************************************************************
//                              Delete Resource
//DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
//****************************************************************************
 private void delete_quality()
    {
    int index= Global.project.getSupplements().getQuality().getSpecificationsList().indexOf(this.qualitySpecification);
    if (this.qualitySpecification!=null && Global.project.getSupplements().getQuality()!=null)
        if (Global.project.getSupplements().getQuality().delete(this.qualitySpecification)==0);
        {
            if (Global.project.getSupplements().getQuality().getSpecificationsList().size()>0)
            {
                if (index==0)
                    this.qualitySpecification = Global.project.getSupplements().getQuality().get(index);
                else
                    this.qualitySpecification = Global.project.getSupplements().getQuality().get(index-1);

                this.populate_quality();
            }
            else
            this.clear_quality();
        }

     this.save_quality();
 }



 // Delete Source
//******************************************************************************

//FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
//****************************************************************************
//                            First & Last Resource
//****************************************************************************
//FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

 private void first_quality()
    {
          if (Global.project!=null &&
         Global.project.getSupplements()!=null && 
         Global.project.getSupplements().getQuality()!=null && 
         Global.project.getSupplements().getQuality().getFirst()!=null)
     {
        this.save_quality();
        this.qualitySpecification=Global.project.getSupplements().getQuality().getFirst();
      }
        this.populate_quality();

 }

 //****************************************************************************
 private void last_quality()
    {
     if (Global.project!=null &&
         Global.project.getSupplements()!=null &&
         Global.project.getSupplements().getQuality()!=null &&
         Global.project.getSupplements().getQuality().getLast()!=null)

     {
         this.save_quality();
         this.qualitySpecification=Global.project.getSupplements().getQuality().getLast();
     }
        this.populate_quality();

 }

//NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
//****************************************************************************
//                     Next Resource & Source
//****************************************************************************
//NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 private void next_quality()
    {
      if(Global.project.getSupplements().getQuality()!=null)
        {
            if (this.qualitySpecification!=null)
            {
                if (Global.project.getSupplements().getQuality().getNext(this.qualitySpecification)!=null)
                {
                    this.save_quality();
                    this.qualitySpecification=Global.project.getSupplements().getQuality().getNext(this.qualitySpecification);
                    this.populate_quality();
                }
            }
        }
        //else
            //System.out.print("No Phase PreRequisits is found yet ");
    }

//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
//****************************************************************************
//                     Previous Resource& Source
//****************************************************************************
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
 private void previous_quality()
    {
      if(Global.project.getSupplements().getQuality()!=null)
        {
            if (this.qualitySpecification!=null)
            {
                if (Global.project.getSupplements().getQuality().getPrevious(this.qualitySpecification)!=null)
                {
                    this.save_quality();
                    this.qualitySpecification=Global.project.getSupplements().getQuality().getPrevious(this.qualitySpecification);
                    this.populate_quality();
                }
            }
        }
        //else
            //System.out.print("No Phase PreRequisits is found yet ");
    }


//CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
//****************************************************************************
//                     Clear Source Resource & Source
//****************************************************************************
 //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

 private void clear_qualityForm()
{
     this.URL_jTextField.setText("");
     this.Description_jTextArea.setText("");
     this.Release_jTextField.setText("");
     this.Type_jComboBox.setSelectedIndex(0);
     this.Domain_jComboBox.setSelectedIndex(0);
 }

 //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 //                              Clear Source
 //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 private void clear_quality( )
{
     this.clear_qualityForm();
     this.qualitySpecification=null;
 }

//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
//****************************************************************************
//                             Populate
//****************************************************************************
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP

private void populateForm()
{  
    this.repaint();
    this.pack();
}


//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
//                         Populate Resource Form
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
 private void populate_quality()
{
     this.clear_qualityForm();
     
         if (this.qualitySpecification!=null && qualitySpecification.getSpecificationURL()!=null)
            this.URL_jTextField.setText(qualitySpecification.getSpecificationURL().toString());
         else
           this.URL_jTextField.setText("");
         //--------------------------------------------------------------------
         if (this.qualitySpecification!=null && qualitySpecification.getDescription()!=null)
            this.Description_jTextArea.setText(qualitySpecification.getDescription());
         else
           this.Description_jTextArea.setText("");
         //--------------------------------------------------------------------
         if (this.qualitySpecification!=null && qualitySpecification.getRelease()!=null)
            this.Release_jTextField.setText(qualitySpecification.getRelease());
         else
           this.Release_jTextField.setText("");

         //--------------------------------------------------------------------
         if (this.qualitySpecification!=null && qualitySpecification.getDomainType()!=null)
            this.Domain_jComboBox.setSelectedIndex(qualitySpecification.getDomainType().ordinal()+1);
         else
             this.Domain_jComboBox.setSelectedIndex(0);

        if (this.qualitySpecification!=null && qualitySpecification.getQualityType()!=null)
            this.Type_jComboBox.setSelectedIndex(qualitySpecification.getQualityType().ordinal()+1);
        else
            this.Type_jComboBox.setSelectedIndex(0);


     this.populateForm();
 }







}
