/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StudyForm.java
 *
 * Created on 06-Nov-2010, 21:56:59
 */

package gui.form.input;
import global.Config;
import global.Global;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import process_model.process.input.Inputs;
import process_model.process.input.data.MetabolomicsData;
import process_model.process.input.data.utility.Attribute;
import process_model.process.input.study.Assay;
import process_model.process.input.study.Instrument;
import process_model.process.input.study.MetabolomicsStudy;
import process_model.process.input.study.ResearchInvestigation;
import process_model.process.input.study.Sample;
import project.Project;
import toolbox.Tools;
import toolbox.datatools.XMLTools;

/**
 *
 * @author amb04
 */
public class StudyForm extends javax.swing.JFrame {
 MetabolomicsData metabolomicsData;
 MetabolomicsStudy metabolomicsStudy;
 private String approaches[]={"","Metabolic Fingerprinting","Metabolic Footprinting", "Metabolite Profiling", "Metabolite Target Analysis", "True Metabolomics" };
 private String dataFormats[]={"","Metabolites Concentration","Peak List", "Spectra", "Spectra Bins","Other"};
    /** Creates new form StudyForm */
    public StudyForm() {
        initComponents();
        if (Global.project!=null && Global.project.getInputs()!=null &&
            Global.project.getInputs().getMetabolomicsData()!=null)
        {
            this.metabolomicsData=Global.project.getInputs().getMetabolomicsData();
        }
        this.refresh();
        this.populate_metabolomicsStudy();
        this.setTitle("Metabolomics Study                           "+Global.project.getProcess().getTitle());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        Data_jDesktopPane = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataSet_jList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        MetaData_jList = new javax.swing.JList();
        Assay_jDesktopPane = new javax.swing.JDesktopPane();
        Assay_InstrumentalTechnique_jTextField = new javax.swing.JTextField();
        Planning_Planner_Name_jLabel32 = new javax.swing.JLabel();
        Planning_Planner_Name_jLabel24 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Assay_Instrument_Info_jTextArea = new javax.swing.JTextArea();
        Assay_DataFormat_jComboBox = new javax.swing.JComboBox();
        Planning_Planner_Name_jLabel33 = new javax.swing.JLabel();
        Planning_Planner_Name_jLabel34 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        Assay_PreProcessing_jTextArea = new javax.swing.JTextArea();
        Planning_Planner_Name_jLabel37 = new javax.swing.JLabel();
        Assay_Runs_jTextField = new javax.swing.JTextField();
        Planning_Planner_Name_jLabel38 = new javax.swing.JLabel();
        Assay_Replica_jTextField = new javax.swing.JTextField();
        Planning_Planner_Name_jLabel36 = new javax.swing.JLabel();
        Assay_FileFormat_jTextField = new javax.swing.JTextField();
        Investigation_jDesktopPane = new javax.swing.JDesktopPane();
        Planning_Planner_Name_jLabel35 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Investigation_ResearchQuestion_jTextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        Investigation_Goals_jTextArea = new javax.swing.JTextArea();
        Planning_Planner_Name_jLabel39 = new javax.swing.JLabel();
        Data_jButton = new javax.swing.JButton();
        Refresh_jButton = new javax.swing.JButton();
        Help_jButton = new javax.swing.JButton();
        Study_jDesktopPane = new javax.swing.JDesktopPane();
        Planning_Planner_Name_jLabel31 = new javax.swing.JLabel();
        Study_Approach_jComboBox = new javax.swing.JComboBox();
        jScrollPane13 = new javax.swing.JScrollPane();
        Study_Aims_jTextArea = new javax.swing.JTextArea();
        Planning_Planner_Name_jLabel40 = new javax.swing.JLabel();
        Sample_jDesktopPane = new javax.swing.JDesktopPane();
        Planning_Planner_Name_jLabel26 = new javax.swing.JLabel();
        Planning_Planner_Name_jLabel27 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        Sample_BioSource_jTextArea = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        Sample_Preparation_jTextArea = new javax.swing.JTextArea();
        Planning_Planner_Name_jLabel30 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        Sample_Type_jTextArea = new javax.swing.JTextArea();
        Planning_Planner_Name_jLabel41 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        Sample_HarvestProtocol_jTextArea = new javax.swing.JTextArea();
        Planning_Planner_Name_jLabel42 = new javax.swing.JLabel();
        Planning_Planner_Name_jLabel28 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        Sample_Standards_jTextArea = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        Sample_GrowthProtocol_jTextArea = new javax.swing.JTextArea();
        save_jButton = new javax.swing.JButton();
        Delete_jButton = new javax.swing.JButton();
        Clear_jButton = new javax.swing.JButton();
        Open_jButton = new javax.swing.JButton();
        Store_jButton = new javax.swing.JButton();
        storeAs_jButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        desktopPane.setBackground(new java.awt.Color(255, 255, 204));
        desktopPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Data_jDesktopPane.setBackground(new java.awt.Color(255, 255, 153));
        Data_jDesktopPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Metabolomics Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        Data_jDesktopPane.setName("Data_jDesktopPane"); // NOI18N
        Data_jDesktopPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Data_jDesktopPaneMouseClicked(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        DataSet_jList.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Set"));
        DataSet_jList.setModel(this.getDataSettAttributesModel());
        DataSet_jList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        DataSet_jList.setName("DataSet_jList"); // NOI18N
        DataSet_jList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                DataSet_jListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(DataSet_jList);

        jScrollPane1.setBounds(10, 20, 220, 50);
        Data_jDesktopPane.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        MetaData_jList.setBorder(javax.swing.BorderFactory.createTitledBorder("Meta-Data"));
        MetaData_jList.setModel(this.getMetaDatatAttributesModel());
        MetaData_jList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        MetaData_jList.setName("MetaData_jList"); // NOI18N
        MetaData_jList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                MetaData_jListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(MetaData_jList);

        jScrollPane2.setBounds(240, 20, 240, 50);
        Data_jDesktopPane.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Data_jDesktopPane.setBounds(450, 520, 490, 80);
        desktopPane.add(Data_jDesktopPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Assay_jDesktopPane.setBackground(new java.awt.Color(255, 255, 153));
        Assay_jDesktopPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assay Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        Assay_jDesktopPane.setName("Assay_jDesktopPane"); // NOI18N
        Assay_jDesktopPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Assay_jDesktopPaneMouseClicked(evt);
            }
        });

        Assay_InstrumentalTechnique_jTextField.setName("Assay_InstrumentalTechnique_jTextField"); // NOI18N
        Assay_InstrumentalTechnique_jTextField.setBounds(10, 40, 180, 20);
        Assay_jDesktopPane.add(Assay_InstrumentalTechnique_jTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_Name_jLabel32.setText("Instrumental Technique");
        Planning_Planner_Name_jLabel32.setName("Planning_Planner_Name_jLabel32"); // NOI18N
        Planning_Planner_Name_jLabel32.setBounds(10, 20, 190, 20);
        Assay_jDesktopPane.add(Planning_Planner_Name_jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_Name_jLabel24.setText("Generated Data Format");
        Planning_Planner_Name_jLabel24.setName("Planning_Planner_Name_jLabel24"); // NOI18N
        Planning_Planner_Name_jLabel24.setBounds(10, 170, 180, 20);
        Assay_jDesktopPane.add(Planning_Planner_Name_jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane8.setName("jScrollPane8"); // NOI18N

        Assay_Instrument_Info_jTextArea.setColumns(20);
        Assay_Instrument_Info_jTextArea.setRows(5);
        Assay_Instrument_Info_jTextArea.setName("Assay_Instrument_Info_jTextArea"); // NOI18N
        jScrollPane8.setViewportView(Assay_Instrument_Info_jTextArea);

        jScrollPane8.setBounds(10, 90, 300, 70);
        Assay_jDesktopPane.add(jScrollPane8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Assay_DataFormat_jComboBox.setMaximumRowCount(10);
        Assay_DataFormat_jComboBox.setModel(new DefaultComboBoxModel(this.dataFormats));
        Assay_DataFormat_jComboBox.setName("Assay_DataFormat_jComboBox"); // NOI18N
        Assay_DataFormat_jComboBox.setBounds(10, 190, 300, 20);
        Assay_jDesktopPane.add(Assay_DataFormat_jComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_Name_jLabel33.setText("Assay Level  PreProcessing Procedures ");
        Planning_Planner_Name_jLabel33.setName("Planning_Planner_Name_jLabel33"); // NOI18N
        Planning_Planner_Name_jLabel33.setBounds(320, 70, 250, 20);
        Assay_jDesktopPane.add(Planning_Planner_Name_jLabel33, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_Name_jLabel34.setText("Instrument Information");
        Planning_Planner_Name_jLabel34.setName("Planning_Planner_Name_jLabel34"); // NOI18N
        Planning_Planner_Name_jLabel34.setBounds(10, 70, 180, 20);
        Assay_jDesktopPane.add(Planning_Planner_Name_jLabel34, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane10.setName("jScrollPane10"); // NOI18N

        Assay_PreProcessing_jTextArea.setColumns(20);
        Assay_PreProcessing_jTextArea.setRows(5);
        Assay_PreProcessing_jTextArea.setName("Assay_PreProcessing_jTextArea"); // NOI18N
        jScrollPane10.setViewportView(Assay_PreProcessing_jTextArea);

        jScrollPane10.setBounds(320, 90, 290, 70);
        Assay_jDesktopPane.add(jScrollPane10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_Name_jLabel37.setText("Number of Replicas");
        Planning_Planner_Name_jLabel37.setName("Planning_Planner_Name_jLabel37"); // NOI18N
        Planning_Planner_Name_jLabel37.setBounds(330, 20, 120, 20);
        Assay_jDesktopPane.add(Planning_Planner_Name_jLabel37, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Assay_Runs_jTextField.setBackground(new java.awt.Color(255, 255, 204));
        Assay_Runs_jTextField.setName("Assay_Runs_jTextField"); // NOI18N
        Assay_Runs_jTextField.setBounds(210, 40, 100, 20);
        Assay_jDesktopPane.add(Assay_Runs_jTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_Name_jLabel38.setText("Number of Runs");
        Planning_Planner_Name_jLabel38.setName("Planning_Planner_Name_jLabel38"); // NOI18N
        Planning_Planner_Name_jLabel38.setBounds(210, 20, 120, 20);
        Assay_jDesktopPane.add(Planning_Planner_Name_jLabel38, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Assay_Replica_jTextField.setBackground(new java.awt.Color(255, 255, 204));
        Assay_Replica_jTextField.setName("Assay_Replica_jTextField"); // NOI18N
        Assay_Replica_jTextField.setBounds(330, 40, 280, 20);
        Assay_jDesktopPane.add(Assay_Replica_jTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_Name_jLabel36.setText("File Format");
        Planning_Planner_Name_jLabel36.setName("Planning_Planner_Name_jLabel36"); // NOI18N
        Planning_Planner_Name_jLabel36.setBounds(330, 170, 250, 20);
        Assay_jDesktopPane.add(Planning_Planner_Name_jLabel36, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Assay_FileFormat_jTextField.setName("Assay_FileFormat_jTextField"); // NOI18N
        Assay_FileFormat_jTextField.setBounds(330, 190, 280, 20);
        Assay_jDesktopPane.add(Assay_FileFormat_jTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Assay_jDesktopPane.setBounds(320, 100, 630, 220);
        desktopPane.add(Assay_jDesktopPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Investigation_jDesktopPane.setBackground(new java.awt.Color(255, 255, 153));
        Investigation_jDesktopPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resaerch Investigation Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        Investigation_jDesktopPane.setName("Investigation_jDesktopPane"); // NOI18N
        Investigation_jDesktopPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Investigation_jDesktopPaneMouseClicked(evt);
            }
        });

        Planning_Planner_Name_jLabel35.setText("Investigation Goals");
        Planning_Planner_Name_jLabel35.setName("Planning_Planner_Name_jLabel35"); // NOI18N
        Planning_Planner_Name_jLabel35.setBounds(10, 120, 390, 20);
        Investigation_jDesktopPane.add(Planning_Planner_Name_jLabel35, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane4.setName("jScrollPane4"); // NOI18N

        Investigation_ResearchQuestion_jTextArea.setColumns(20);
        Investigation_ResearchQuestion_jTextArea.setRows(5);
        Investigation_ResearchQuestion_jTextArea.setName("Investigation_ResearchQuestion_jTextArea"); // NOI18N
        jScrollPane4.setViewportView(Investigation_ResearchQuestion_jTextArea);

        jScrollPane4.setBounds(10, 40, 280, 70);
        Investigation_jDesktopPane.add(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane6.setName("jScrollPane6"); // NOI18N

        Investigation_Goals_jTextArea.setColumns(20);
        Investigation_Goals_jTextArea.setRows(5);
        Investigation_Goals_jTextArea.setName("Investigation_Goals_jTextArea"); // NOI18N
        jScrollPane6.setViewportView(Investigation_Goals_jTextArea);

        jScrollPane6.setBounds(10, 140, 280, 70);
        Investigation_jDesktopPane.add(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_Name_jLabel39.setText(" Investigation Reserach Question");
        Planning_Planner_Name_jLabel39.setName("Planning_Planner_Name_jLabel39"); // NOI18N
        Planning_Planner_Name_jLabel39.setBounds(10, 20, 390, 20);
        Investigation_jDesktopPane.add(Planning_Planner_Name_jLabel39, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Investigation_jDesktopPane.setBounds(10, 100, 300, 220);
        desktopPane.add(Investigation_jDesktopPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Data_jButton.setText("Metabolomics Data");
        Data_jButton.setName("Data_jButton"); // NOI18N
        Data_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_jButtonActionPerformed(evt);
            }
        });
        Data_jButton.setBounds(710, 620, 160, 24);
        desktopPane.add(Data_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Refresh_jButton.setText("Refresh");
        Refresh_jButton.setName("Refresh_jButton"); // NOI18N
        Refresh_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_jButtonActionPerformed(evt);
            }
        });
        Refresh_jButton.setBounds(100, 620, 90, 24);
        desktopPane.add(Refresh_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Help_jButton.setText("Help");
        Help_jButton.setName("Help_jButton"); // NOI18N
        Help_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_jButtonActionPerformed(evt);
            }
        });
        Help_jButton.setBounds(870, 620, 80, 24);
        desktopPane.add(Help_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Study_jDesktopPane.setBackground(new java.awt.Color(255, 255, 153));
        Study_jDesktopPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Metabolomics Study Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        Study_jDesktopPane.setName("Study_jDesktopPane"); // NOI18N
        Study_jDesktopPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Study_jDesktopPaneMouseClicked(evt);
            }
        });

        Planning_Planner_Name_jLabel31.setText("Approach");
        Planning_Planner_Name_jLabel31.setName("Planning_Planner_Name_jLabel31"); // NOI18N
        Planning_Planner_Name_jLabel31.setBounds(20, 30, 90, 22);
        Study_jDesktopPane.add(Planning_Planner_Name_jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Study_Approach_jComboBox.setMaximumRowCount(10);
        Study_Approach_jComboBox.setModel(new DefaultComboBoxModel(this.approaches));
        Study_Approach_jComboBox.setName("Study_Approach_jComboBox"); // NOI18N
        Study_Approach_jComboBox.setBounds(110, 30, 200, 22);
        Study_jDesktopPane.add(Study_Approach_jComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane13.setName("jScrollPane13"); // NOI18N

        Study_Aims_jTextArea.setColumns(20);
        Study_Aims_jTextArea.setRows(5);
        Study_Aims_jTextArea.setName("Study_Aims_jTextArea"); // NOI18N
        jScrollPane13.setViewportView(Study_Aims_jTextArea);

        jScrollPane13.setBounds(440, 20, 490, 50);
        Study_jDesktopPane.add(jScrollPane13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_Name_jLabel40.setText("Aims of Study");
        Planning_Planner_Name_jLabel40.setName("Planning_Planner_Name_jLabel40"); // NOI18N
        Planning_Planner_Name_jLabel40.setBounds(340, 30, 100, 20);
        Study_jDesktopPane.add(Planning_Planner_Name_jLabel40, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Study_jDesktopPane.setBounds(10, 10, 940, 80);
        desktopPane.add(Study_jDesktopPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Sample_jDesktopPane.setBackground(new java.awt.Color(255, 255, 153));
        Sample_jDesktopPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sample Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        Sample_jDesktopPane.setName("Sample_jDesktopPane"); // NOI18N
        Sample_jDesktopPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sample_jDesktopPaneMouseClicked(evt);
            }
        });

        Planning_Planner_Name_jLabel26.setText("Bio-Source");
        Planning_Planner_Name_jLabel26.setName("Planning_Planner_Name_jLabel26"); // NOI18N
        Planning_Planner_Name_jLabel26.setBounds(10, 30, 130, 20);
        Sample_jDesktopPane.add(Planning_Planner_Name_jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_Name_jLabel27.setText("Sample  Preparation");
        Planning_Planner_Name_jLabel27.setName("Planning_Planner_Name_jLabel27"); // NOI18N
        Planning_Planner_Name_jLabel27.setBounds(440, 100, 130, 20);
        Sample_jDesktopPane.add(Planning_Planner_Name_jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane9.setName("jScrollPane9"); // NOI18N

        Sample_BioSource_jTextArea.setColumns(20);
        Sample_BioSource_jTextArea.setRows(5);
        Sample_BioSource_jTextArea.setName("Sample_BioSource_jTextArea"); // NOI18N
        jScrollPane9.setViewportView(Sample_BioSource_jTextArea);

        jScrollPane9.setBounds(140, 30, 260, 30);
        Sample_jDesktopPane.add(jScrollPane9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane11.setName("jScrollPane11"); // NOI18N

        Sample_Preparation_jTextArea.setColumns(20);
        Sample_Preparation_jTextArea.setRows(5);
        Sample_Preparation_jTextArea.setName("Sample_Preparation_jTextArea"); // NOI18N
        jScrollPane11.setViewportView(Sample_Preparation_jTextArea);

        jScrollPane11.setBounds(440, 120, 490, 60);
        Sample_jDesktopPane.add(jScrollPane11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_Name_jLabel30.setText("Growth Protocols");
        Planning_Planner_Name_jLabel30.setName("Planning_Planner_Name_jLabel30"); // NOI18N
        Planning_Planner_Name_jLabel30.setBounds(10, 150, 130, 20);
        Sample_jDesktopPane.add(Planning_Planner_Name_jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane12.setName("jScrollPane12"); // NOI18N

        Sample_Type_jTextArea.setColumns(20);
        Sample_Type_jTextArea.setRows(5);
        Sample_Type_jTextArea.setName("Sample_Type_jTextArea"); // NOI18N
        jScrollPane12.setViewportView(Sample_Type_jTextArea);

        jScrollPane12.setBounds(140, 70, 260, 30);
        Sample_jDesktopPane.add(jScrollPane12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_Name_jLabel41.setText("Sample Type");
        Planning_Planner_Name_jLabel41.setName("Planning_Planner_Name_jLabel41"); // NOI18N
        Planning_Planner_Name_jLabel41.setBounds(10, 70, 130, 20);
        Sample_jDesktopPane.add(Planning_Planner_Name_jLabel41, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane14.setName("jScrollPane14"); // NOI18N

        Sample_HarvestProtocol_jTextArea.setColumns(20);
        Sample_HarvestProtocol_jTextArea.setRows(5);
        Sample_HarvestProtocol_jTextArea.setName("Sample_HarvestProtocol_jTextArea"); // NOI18N
        jScrollPane14.setViewportView(Sample_HarvestProtocol_jTextArea);

        jScrollPane14.setBounds(440, 40, 490, 60);
        Sample_jDesktopPane.add(jScrollPane14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_Name_jLabel42.setText("Harvest Protocols");
        Planning_Planner_Name_jLabel42.setName("Planning_Planner_Name_jLabel42"); // NOI18N
        Planning_Planner_Name_jLabel42.setBounds(440, 20, 130, 20);
        Sample_jDesktopPane.add(Planning_Planner_Name_jLabel42, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Planning_Planner_Name_jLabel28.setText("Added Satandards");
        Planning_Planner_Name_jLabel28.setName("Planning_Planner_Name_jLabel28"); // NOI18N
        Planning_Planner_Name_jLabel28.setBounds(10, 110, 120, 20);
        Sample_jDesktopPane.add(Planning_Planner_Name_jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane15.setName("jScrollPane15"); // NOI18N

        Sample_Standards_jTextArea.setColumns(20);
        Sample_Standards_jTextArea.setRows(5);
        Sample_Standards_jTextArea.setName("Sample_Standards_jTextArea"); // NOI18N
        jScrollPane15.setViewportView(Sample_Standards_jTextArea);

        jScrollPane15.setBounds(140, 110, 260, 30);
        Sample_jDesktopPane.add(jScrollPane15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane16.setName("jScrollPane16"); // NOI18N

        Sample_GrowthProtocol_jTextArea.setColumns(20);
        Sample_GrowthProtocol_jTextArea.setRows(5);
        Sample_GrowthProtocol_jTextArea.setName("Sample_GrowthProtocol_jTextArea"); // NOI18N
        jScrollPane16.setViewportView(Sample_GrowthProtocol_jTextArea);

        jScrollPane16.setBounds(10, 170, 390, 90);
        Sample_jDesktopPane.add(jScrollPane16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Sample_jDesktopPane.setBounds(10, 330, 940, 280);
        desktopPane.add(Sample_jDesktopPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        save_jButton.setText("Save");
        save_jButton.setName("save_jButton"); // NOI18N
        save_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_jButtonActionPerformed(evt);
            }
        });
        save_jButton.setBounds(10, 620, 90, 24);
        desktopPane.add(save_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Delete_jButton.setText("Delete");
        Delete_jButton.setName("Delete_jButton"); // NOI18N
        Delete_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_jButtonActionPerformed(evt);
            }
        });
        Delete_jButton.setBounds(270, 620, 80, 24);
        desktopPane.add(Delete_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Clear_jButton.setText("Clear");
        Clear_jButton.setName("Clear_jButton"); // NOI18N
        Clear_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_jButtonActionPerformed(evt);
            }
        });
        Clear_jButton.setBounds(190, 620, 80, 24);
        desktopPane.add(Clear_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Open_jButton.setText("Load File");
        Open_jButton.setName("Open_jButton"); // NOI18N
        Open_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_jButtonActionPerformed(evt);
            }
        });
        Open_jButton.setBounds(360, 620, 120, 25);
        desktopPane.add(Open_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Store_jButton.setText("Store");
        Store_jButton.setName("Store_jButton"); // NOI18N
        Store_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Store_jButtonActionPerformed(evt);
            }
        });
        Store_jButton.setBounds(600, 620, 100, 25);
        desktopPane.add(Store_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        storeAs_jButton.setText("Store As");
        storeAs_jButton.setName("storeAs_jButton"); // NOI18N
        storeAs_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeAs_jButtonActionPerformed(evt);
            }
        });
        storeAs_jButton.setBounds(480, 620, 120, 25);
        desktopPane.add(storeAs_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sample_jDesktopPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sample_jDesktopPaneMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_Sample_jDesktopPaneMouseClicked

    private void Data_jDesktopPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Data_jDesktopPaneMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_Data_jDesktopPaneMouseClicked

    private void Assay_jDesktopPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Assay_jDesktopPaneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Assay_jDesktopPaneMouseClicked

    private void Data_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_jButtonActionPerformed
 new DataForm().setVisible(true);
    }//GEN-LAST:event_Data_jButtonActionPerformed

    private void Investigation_jDesktopPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Investigation_jDesktopPaneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Investigation_jDesktopPaneMouseClicked

    private void Refresh_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_jButtonActionPerformed
   this.refresh();
   this.populate_metabolomicsStudy();
   
    }//GEN-LAST:event_Refresh_jButtonActionPerformed

    private void Help_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_jButtonActionPerformed

//        if (new File(Config.helpLocation + "study.pdf").exists())
            Tools.viewAnyFile(new File(Config.helpLocation + "study.pdf"));
//        else
//            JOptionPane.showMessageDialog(null, "Help file was not found!");

    }//GEN-LAST:event_Help_jButtonActionPerformed

    private void MetaData_jListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_MetaData_jListValueChanged
        // TODO add your handling code here:
}//GEN-LAST:event_MetaData_jListValueChanged

    private void DataSet_jListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_DataSet_jListValueChanged
        // TODO add your handling code here:
}//GEN-LAST:event_DataSet_jListValueChanged

    private void Study_jDesktopPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Study_jDesktopPaneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Study_jDesktopPaneMouseClicked

    private void save_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_jButtonActionPerformed
    this.save_metabolomicsStudy();
    }//GEN-LAST:event_save_jButtonActionPerformed

    private void Delete_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_jButtonActionPerformed

    this.populateForm();
    
    if (Global.project!=null && Global.project.getInputs()!=null &&
         Global.project.getInputs().getMetabolomicsStudy()!=null &&
         this.metabolomicsStudy!=null)
    {
         int decision=JOptionPane.showConfirmDialog(null, "Are you sure You want to delete the study Information");
         if (decision==0)
             Global.project.getInputs().setMetabolomicsStudy(null);
    }
    }//GEN-LAST:event_Delete_jButtonActionPerformed

    private void Clear_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_jButtonActionPerformed
    this.metabolomicsStudy=null;
    this.populate_metabolomicsStudy();

    }//GEN-LAST:event_Clear_jButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
//    System.runFinalization();
    System.gc();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void Store_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Store_jButtonActionPerformed

            this.save_metabolomicsStudy();
            if (this.metabolomicsStudy!=null)
                this.metabolomicsStudy.store();
    
    }//GEN-LAST:event_Store_jButtonActionPerformed

    private void Open_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_jButtonActionPerformed

    // does the actual work 
     MetabolomicsStudy loadedMetabolomicsStudy=(MetabolomicsStudy) XMLTools.loadObject(new MetabolomicsStudy(),null);
     if (loadedMetabolomicsStudy!=null)                                            
         this.metabolomicsStudy = loadedMetabolomicsStudy.clone();
     
     this.refresh();
     this.populate_metabolomicsStudy();
     this.populateForm();

    }//GEN-LAST:event_Open_jButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
this.save_metabolomicsStudy();
    }//GEN-LAST:event_formWindowClosing

    private void storeAs_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeAs_jButtonActionPerformed

      this.save_metabolomicsStudy();         
      if (this.metabolomicsStudy != null)            
          this.metabolomicsStudy.store(null);        
        
    }//GEN-LAST:event_storeAs_jButtonActionPerformed


//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
//****************************************************************************
//                              Save study
//****************************************************************************
//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

 private void save_metabolomicsStudy()
 {
     if (this.metabolomicsStudy==null)
        this.metabolomicsStudy=new MetabolomicsStudy();

     if (this.Study_Aims_jTextArea.getText()!=null && (!this.Study_Aims_jTextArea.getText().equals("")))
        this.metabolomicsStudy.setAims(this.Study_Aims_jTextArea.getText());

    if (this.Study_Approach_jComboBox.getSelectedIndex()>0)
        this.metabolomicsStudy.setApproachIndex(this.Study_Approach_jComboBox.getSelectedIndex());

    //---------------------------------------------------------------------------------------------------------------------
    if (this.metabolomicsStudy.getInvestigation()==null)
        this.metabolomicsStudy.setInvestigation(new ResearchInvestigation());

    if (this.Investigation_ResearchQuestion_jTextArea.getText()!=null && (!this.Investigation_ResearchQuestion_jTextArea.getText().equals("")))
        this.metabolomicsStudy.getInvestigation().setQuestion(this.Investigation_ResearchQuestion_jTextArea.getText());

    if (this.Investigation_Goals_jTextArea.getText()!=null && !this.Investigation_Goals_jTextArea.getText().equals(""))
        this.metabolomicsStudy.getInvestigation().setGoal(this.Investigation_Goals_jTextArea.getText());
  //---------------------------------------------------------------------------------------------------------------------
    if (this.metabolomicsStudy.getAssay()==null)
        this.metabolomicsStudy.setAssay(new Assay());
     
    if (this.Assay_InstrumentalTechnique_jTextField.getText()!=null && (!this.Assay_InstrumentalTechnique_jTextField.getText().equals("")))
        this.metabolomicsStudy.getAssay().setTechnique(this.Assay_InstrumentalTechnique_jTextField.getText());

     if (this.Assay_FileFormat_jTextField.getText()!=null && (!this.Assay_FileFormat_jTextField.getText().equals("")))
        this.metabolomicsStudy.getAssay().setFileFormat(this.Assay_FileFormat_jTextField.getText());

     if (this.Assay_PreProcessing_jTextArea.getText()!=null && (!this.Assay_PreProcessing_jTextArea.getText().equals("")))
        this.metabolomicsStudy.getAssay().setPreProcessingProcedures(this.Assay_PreProcessing_jTextArea.getText());


    if (this.Assay_Runs_jTextField.getText()!=null && (!this.Assay_Runs_jTextField.getText().equals("")))
        this.metabolomicsStudy.getAssay().setRuns(Integer.parseInt(this.Assay_Runs_jTextField.getText()));

    if (this.Assay_Replica_jTextField.getText()!=null && (!this.Assay_Replica_jTextField.getText().equals("")))
        this.metabolomicsStudy.getAssay().setReplica(Integer.parseInt(this.Assay_Replica_jTextField.getText()));

     if (this.Assay_DataFormat_jComboBox.getSelectedIndex()>0)
        this.metabolomicsStudy.getAssay().setDataFormatIndex(this.Assay_DataFormat_jComboBox.getSelectedIndex());

     //--------------------------------------------------------------------------
       if (this.metabolomicsStudy.getAssay()!=null && this.metabolomicsStudy.getAssay().getSample()==null)
        this.metabolomicsStudy.getAssay().setSample(new Sample());

    if (this.Sample_BioSource_jTextArea.getText()!=null && (!this.Sample_BioSource_jTextArea.getText().equals("")))
        this.metabolomicsStudy.getAssay().getSample().setBioSource(this.Sample_BioSource_jTextArea.getText());

     if (this.Sample_GrowthProtocol_jTextArea.getText()!=null && (!this.Sample_GrowthProtocol_jTextArea.getText().equals("")))
        this.metabolomicsStudy.getAssay().getSample().setGrowthProtocols(this.Sample_GrowthProtocol_jTextArea.getText());

     if (this.Sample_HarvestProtocol_jTextArea.getText()!=null && (!this.Sample_HarvestProtocol_jTextArea.getText().equals("")))
        this.metabolomicsStudy.getAssay().getSample().setHarvestProtocols(this.Sample_HarvestProtocol_jTextArea.getText());

     if (this.Sample_Preparation_jTextArea.getText()!=null && (!this.Sample_Preparation_jTextArea.getText().equals("")))
        this.metabolomicsStudy.getAssay().getSample().setSamplePreparation(this.Sample_Preparation_jTextArea.getText());

     if (this.Sample_Standards_jTextArea.getText()!=null && (!this.Sample_Standards_jTextArea.getText().equals("")))
        this.metabolomicsStudy.getAssay().getSample().setStandards(this.Sample_Standards_jTextArea.getText());

     if (this.Sample_Type_jTextArea.getText()!=null && (!this.Sample_Type_jTextArea.getText().equals("")))
        this.metabolomicsStudy.getAssay().getSample().setSampleType(this.Sample_Type_jTextArea.getText());

     //--------------------------------------------------------------------------
     if (this.metabolomicsStudy.getAssay()!=null && this.metabolomicsStudy.getAssay().getInstrument()==null)
        this.metabolomicsStudy.getAssay().setInstrument(new Instrument());

    if (this.Assay_Instrument_Info_jTextArea.getText()!=null && (!this.Assay_Instrument_Info_jTextArea.getText().equals("")))
        this.metabolomicsStudy.getAssay().getInstrument().setInfo(this.Assay_Instrument_Info_jTextArea.getText());    

    // call save which save study to inputs in project
     if (this.metabolomicsStudy!=null)         
         this.metabolomicsStudy.save();

     if (Global.project!=null && Global.project.getInputs()!=null)
         Global.project.getInputs().store();
     
     this.populate_metabolomicsStudy();
   }

private void refresh()
    {
if (Global.project!=null && Global.project.getInputs()!=null &&
         Global.project.getInputs().getMetabolomicsStudy()!=null)

this.metabolomicsStudy=Global.project.getInputs().getMetabolomicsStudy().clone();

}

//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
//                         Populate Plan Form
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
 private void populate_metabolomicsStudy()
{

     if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getAims()!=null)
        this.Study_Aims_jTextArea.setText(this.metabolomicsStudy.getAims());
     else
         this.Study_Aims_jTextArea.setText("");

     if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getMetabolomicsApproach()!=null)
        this.Study_Approach_jComboBox.setSelectedIndex(this.metabolomicsStudy.getMetabolomicsApproach().ordinal()+1);
     else
         this.Study_Approach_jComboBox.setSelectedIndex(0);

    //---------------------------------------------------------------------------------------------------------------------
     if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getInvestigation()!=null && this.metabolomicsStudy.getInvestigation().getGoal()!=null)
        this.Investigation_Goals_jTextArea.setText(this.metabolomicsStudy.getInvestigation().getGoal());
     else
        this.Investigation_Goals_jTextArea.setText("");

    if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getInvestigation()!=null && this.metabolomicsStudy.getInvestigation().getQuestion()!=null)
        this.Investigation_ResearchQuestion_jTextArea.setText(this.metabolomicsStudy.getInvestigation().getQuestion());
     else
        this.Investigation_ResearchQuestion_jTextArea.setText("");

  //---------------------------------------------------------------------------------------------------------------------

     if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getAssay()!=null && this.metabolomicsStudy.getAssay().getTechnique()!=null)
        this.Assay_InstrumentalTechnique_jTextField.setText(this.metabolomicsStudy.getAssay().getTechnique());
     else
        this.Assay_InstrumentalTechnique_jTextField.setText("");

      if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getAssay()!=null && this.metabolomicsStudy.getAssay().getPreProcessingProcedures()!=null)
        this.Assay_PreProcessing_jTextArea.setText(this.metabolomicsStudy.getAssay().getPreProcessingProcedures());
     else
        this.Assay_PreProcessing_jTextArea.setText("");

    if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getAssay()!=null)
        this.Assay_Runs_jTextField.setText(this.metabolomicsStudy.getAssay().getRuns()+"");
     else
        this.Assay_Runs_jTextField.setText(0+"");

     if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getAssay()!=null)
        this.Assay_Replica_jTextField.setText(this.metabolomicsStudy.getAssay().getReplica()+"");
     else
        this.Assay_Replica_jTextField.setText(0+"");

     if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getAssay()!=null && this.metabolomicsStudy.getAssay().getAssayDataFormat()!=null)
        this.Assay_DataFormat_jComboBox.setSelectedIndex(this.metabolomicsStudy.getAssay().getAssayDataFormat().ordinal()+1);
     else
        this.Assay_DataFormat_jComboBox.setSelectedIndex(0);

     if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getAssay()!=null && this.metabolomicsStudy.getAssay().getFileFormat()!=null)
        this.Assay_FileFormat_jTextField.setText(this.metabolomicsStudy.getAssay().getFileFormat());
     else
        this.Assay_FileFormat_jTextField.setText("");
     //------------------------------------------------------------------------
     if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getAssay()!=null && this.metabolomicsStudy.getAssay().getInstrument()!=null
             && this.metabolomicsStudy.getAssay().getInstrument().getInfo()!=null)
        this.Assay_Instrument_Info_jTextArea.setText(this.metabolomicsStudy.getAssay().getInstrument().getInfo());
     else
        this.Assay_Instrument_Info_jTextArea.setText("");
    //-------------------------------------------------------------------------     
     if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getAssay()!=null && this.metabolomicsStudy.getAssay().getSample()!=null
             && this.metabolomicsStudy.getAssay().getSample().getBioSource()!=null)
        this.Sample_BioSource_jTextArea.setText(this.metabolomicsStudy.getAssay().getSample().getBioSource());
     else
        this.Sample_BioSource_jTextArea.setText("");

     if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getAssay()!=null && this.metabolomicsStudy.getAssay().getSample()!=null
             && this.metabolomicsStudy.getAssay().getSample().getGrowthProtocols()!=null)
        this.Sample_GrowthProtocol_jTextArea.setText(this.metabolomicsStudy.getAssay().getSample().getGrowthProtocols());
     else
        this.Sample_GrowthProtocol_jTextArea.setText("");

     if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getAssay()!=null && this.metabolomicsStudy.getAssay().getSample()!=null
             && this.metabolomicsStudy.getAssay().getSample().getHarvestProtocols()!=null)
        this.Sample_HarvestProtocol_jTextArea.setText(this.metabolomicsStudy.getAssay().getSample().getHarvestProtocols());
     else
        this.Sample_HarvestProtocol_jTextArea.setText("");

     if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getAssay()!=null && this.metabolomicsStudy.getAssay().getSample()!=null
             && this.metabolomicsStudy.getAssay().getSample().getSamplePreparation()!=null)
        this.Sample_Preparation_jTextArea.setText(this.metabolomicsStudy.getAssay().getSample().getSamplePreparation());
     else
        this.Sample_Preparation_jTextArea.setText("");

     if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getAssay()!=null && this.metabolomicsStudy.getAssay().getSample()!=null
             && this.metabolomicsStudy.getAssay().getSample().getSampleType()!=null)
        this.Sample_Type_jTextArea.setText(this.metabolomicsStudy.getAssay().getSample().getSampleType());
     else
        this.Sample_Type_jTextArea.setText("");

     if (this.metabolomicsStudy!=null && this.metabolomicsStudy.getAssay()!=null && this.metabolomicsStudy.getAssay().getSample()!=null
             && this.metabolomicsStudy.getAssay().getSample().getStandards()!=null)
        this.Sample_Standards_jTextArea.setText(this.metabolomicsStudy.getAssay().getSample().getStandards());
     else
        this.Sample_Standards_jTextArea.setText("");
    //*************************************************************************
    this.DataSet_jList.setModel(this.getDataSettAttributesModel());
    this.MetaData_jList.setModel(this.getMetaDatatAttributesModel());
 
this.populateForm();
}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    if (Global.project == null) {
                        Global.project = new Project();
                    }
                    new StudyForm().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(StudyForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(StudyForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Assay_DataFormat_jComboBox;
    private javax.swing.JTextField Assay_FileFormat_jTextField;
    private javax.swing.JTextArea Assay_Instrument_Info_jTextArea;
    private javax.swing.JTextField Assay_InstrumentalTechnique_jTextField;
    private javax.swing.JTextArea Assay_PreProcessing_jTextArea;
    private javax.swing.JTextField Assay_Replica_jTextField;
    private javax.swing.JTextField Assay_Runs_jTextField;
    private javax.swing.JDesktopPane Assay_jDesktopPane;
    private javax.swing.JButton Clear_jButton;
    private javax.swing.JList DataSet_jList;
    private javax.swing.JButton Data_jButton;
    private javax.swing.JDesktopPane Data_jDesktopPane;
    private javax.swing.JButton Delete_jButton;
    private javax.swing.JButton Help_jButton;
    private javax.swing.JTextArea Investigation_Goals_jTextArea;
    private javax.swing.JTextArea Investigation_ResearchQuestion_jTextArea;
    private javax.swing.JDesktopPane Investigation_jDesktopPane;
    private javax.swing.JList MetaData_jList;
    private javax.swing.JButton Open_jButton;
    private javax.swing.JLabel Planning_Planner_Name_jLabel24;
    private javax.swing.JLabel Planning_Planner_Name_jLabel26;
    private javax.swing.JLabel Planning_Planner_Name_jLabel27;
    private javax.swing.JLabel Planning_Planner_Name_jLabel28;
    private javax.swing.JLabel Planning_Planner_Name_jLabel30;
    private javax.swing.JLabel Planning_Planner_Name_jLabel31;
    private javax.swing.JLabel Planning_Planner_Name_jLabel32;
    private javax.swing.JLabel Planning_Planner_Name_jLabel33;
    private javax.swing.JLabel Planning_Planner_Name_jLabel34;
    private javax.swing.JLabel Planning_Planner_Name_jLabel35;
    private javax.swing.JLabel Planning_Planner_Name_jLabel36;
    private javax.swing.JLabel Planning_Planner_Name_jLabel37;
    private javax.swing.JLabel Planning_Planner_Name_jLabel38;
    private javax.swing.JLabel Planning_Planner_Name_jLabel39;
    private javax.swing.JLabel Planning_Planner_Name_jLabel40;
    private javax.swing.JLabel Planning_Planner_Name_jLabel41;
    private javax.swing.JLabel Planning_Planner_Name_jLabel42;
    private javax.swing.JButton Refresh_jButton;
    private javax.swing.JTextArea Sample_BioSource_jTextArea;
    private javax.swing.JTextArea Sample_GrowthProtocol_jTextArea;
    private javax.swing.JTextArea Sample_HarvestProtocol_jTextArea;
    private javax.swing.JTextArea Sample_Preparation_jTextArea;
    private javax.swing.JTextArea Sample_Standards_jTextArea;
    private javax.swing.JTextArea Sample_Type_jTextArea;
    private javax.swing.JDesktopPane Sample_jDesktopPane;
    private javax.swing.JButton Store_jButton;
    private javax.swing.JTextArea Study_Aims_jTextArea;
    private javax.swing.JComboBox Study_Approach_jComboBox;
    private javax.swing.JDesktopPane Study_jDesktopPane;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton save_jButton;
    private javax.swing.JButton storeAs_jButton;
    // End of variables declaration//GEN-END:variables



//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
//****************************************************************************
//                             Populate
//****************************************************************************
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP

private void populateForm()
{
    this.setTitle("Metabolomics Data");
    this.repaint();
    this.pack();
 }


//COMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOC
//                       Get Project Attributes Model
//COMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOC
public  DefaultComboBoxModel getDataSettAttributesModel()
{
  DefaultComboBoxModel dcm=null;
  ArrayList<Attribute> attributesList=new ArrayList<Attribute>();
  String[] attributesArrayNames = null;
  if (metabolomicsData!=null && metabolomicsData.getDataSet()!=null && !metabolomicsData.getDataSet().isExternal())
  {
    if (metabolomicsData.getDataSet().getAttributesList()!=null
              && metabolomicsData.getDataSet().getAttributesList().size()>0)
      {
        attributesList=metabolomicsData.getDataSet().getAttributesList();
        int size=attributesList.size();
        attributesArrayNames = new String[size];
        int i=0;
        for (Object o:attributesList)
            {
              Attribute thisAttribute=(Attribute) o;
              attributesArrayNames[i]=thisAttribute.toString();
              i=i+1;
             }
        dcm=new DefaultComboBoxModel(attributesArrayNames);
        return dcm;
        }
     else
      {
        String names[] ={"<No attribute available yet>"};
        dcm=new DefaultComboBoxModel(names);
        return dcm;
      }
  }
 else
    {
    String names[] ={"<No attribute available yet>"};
    dcm=new DefaultComboBoxModel(names);
     return dcm;
    }
 }

//COMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOC
//                       Get Project Attributes Model
//COMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOCOMPOC
public  DefaultComboBoxModel getMetaDatatAttributesModel()
{
  DefaultComboBoxModel dcm=null;
  ArrayList<Attribute> attributesList=new ArrayList<Attribute>();
  String[] attributesArrayNames = null;
  if (metabolomicsData!=null && metabolomicsData.getMetaData()!=null && !metabolomicsData.getMetaData().isExternal())
  {
    if (metabolomicsData.getMetaData().getAttributesList()!=null
              && metabolomicsData.getMetaData().getAttributesList().size()>0)
      {
        attributesList=metabolomicsData.getMetaData().getAttributesList();
        int size=attributesList.size();
        attributesArrayNames = new String[size];
        int i=0;
        for (Object o:attributesList)
            {
              Attribute thisAttribute=(Attribute) o;
              attributesArrayNames[i]=thisAttribute.toString();
              i=i+1;
             }
        dcm=new DefaultComboBoxModel(attributesArrayNames);
        return dcm;
        }
     else
      {
        String names[] ={"<No attribute available yet>"};
        dcm=new DefaultComboBoxModel(names);
        return dcm;
      }
  }
 else
    {
    String names[] ={"<No attribute available yet>"};
    dcm=new DefaultComboBoxModel(names);
     return dcm;
    }
 }




}
