package toolbox.viewtools;


import weka.core.Instances;
import weka.gui.AttributeVisualizationPanel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomisedAttributeVisualizationPanel.java
 *
 * Created on 25-Jun-2011, 22:39:07
 */

/**
 *
 * @author amb04
 */
public class CustomisedAttributeVisualizationPanel extends javax.swing.JPanel {
private Instances instances=null;
private int attributeIndex=0;
    /** Creates new form CustomisedAttributeVisualizationPanel */
    public CustomisedAttributeVisualizationPanel(AttributeVisualizationPanel attributeVisualizationPanel, Instances instances, int attributeIndex)
    {
        this.instances=instances;
        this.attributeIndex=attributeIndex;
        initComponents();


        String name=attributeVisualizationPanel.getName();
        Border_jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(name));

       javax.swing.GroupLayout attributeVisualizationPanelLayout = new javax.swing.GroupLayout(attributeVisualizationPanel);
        attributeVisualizationPanel.setLayout(attributeVisualizationPanelLayout);
        attributeVisualizationPanelLayout.setHorizontalGroup(
            attributeVisualizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );
        attributeVisualizationPanelLayout.setVerticalGroup(
            attributeVisualizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Visualization_jPanelLayout = new javax.swing.GroupLayout(Visualization_jPanel);
        Visualization_jPanel.setLayout(Visualization_jPanelLayout);
        Visualization_jPanelLayout.setHorizontalGroup(
            Visualization_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Visualization_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attributeVisualizationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Visualization_jPanelLayout.setVerticalGroup(
            Visualization_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Visualization_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attributeVisualizationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );


    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Border_jPanel = new javax.swing.JPanel();
        Visualization_jPanel = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(150, 150));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        Border_jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Attribute"));
        Border_jPanel.setName("Border_jPanel"); // NOI18N
        Border_jPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Border_jPanelMouseClicked(evt);
            }
        });

        Visualization_jPanel.setName("Visualization_jPanel"); // NOI18N
        Visualization_jPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Visualization_jPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Visualization_jPanelLayout = new javax.swing.GroupLayout(Visualization_jPanel);
        Visualization_jPanel.setLayout(Visualization_jPanelLayout);
        Visualization_jPanelLayout.setHorizontalGroup(
            Visualization_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        Visualization_jPanelLayout.setVerticalGroup(
            Visualization_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Border_jPanelLayout = new javax.swing.GroupLayout(Border_jPanel);
        Border_jPanel.setLayout(Border_jPanelLayout);
        Border_jPanelLayout.setHorizontalGroup(
            Border_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Border_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Visualization_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Border_jPanelLayout.setVerticalGroup(
            Border_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Border_jPanelLayout.createSequentialGroup()
                .addComponent(Visualization_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Border_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Border_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Visualization_jPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Visualization_jPanelMouseClicked

   VisualizationTools.visualizeAttribute(instances, attributeIndex);
        
    }//GEN-LAST:event_Visualization_jPanelMouseClicked

    private void Border_jPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Border_jPanelMouseClicked
        VisualizationTools.visualizeAttribute(instances, attributeIndex);
    }//GEN-LAST:event_Border_jPanelMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
VisualizationTools.visualizeAttribute(instances, attributeIndex);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Border_jPanel;
    private javax.swing.JPanel Visualization_jPanel;
    // End of variables declaration//GEN-END:variables

}
