/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModelVisualization_JFrame.java
 *
 * Created on 22-Jul-2011, 07:45:14
 */
package toolbox.viewtools;

import java.io.File;
import toolbox.Tools;

/**
 *
 * @author amb04
 */
public class ModelVisualization_JFrame extends javax.swing.JFrame {

    /** Creates new form ModelVisualization_JFrame */
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++    
    public ModelVisualization_JFrame(File imageFile) 
    {
        initComponents();              
        this.setVisible(true);
        if (imageFile!=null && imageFile.exists())
        {
            Model_jTextArea.enable(false);
            Model_jTextArea.setVisible(false);
            //-----------------------------------------------------------------
            model_jLabel.enable(true);
            model_jLabel.setVisible(true);
            //-----------------------------------------------------------------            
            model_jLabel.setIcon(new javax.swing.ImageIcon(Tools.toURL(imageFile))); // NOI18N
            
            
        }
//        else
//            System.out.println(" image file was not found");
    this.pack();
    this.repaint();
    }
    
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    public ModelVisualization_JFrame(String displayText) 
    {
        initComponents();              
        this.setVisible(true);
        if (displayText!=null)
        {            
            model_jLabel.enable(false);
            model_jLabel.setVisible(false);
            
            Model_jTextArea.enable(true);
            Model_jTextArea.setVisible(true);            
            
            Model_jTextArea.setText(displayText);
        }
//        else
//            System.out.println(" no text to be displayed");
    this.pack();
    this.repaint();
    }
   
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @Override
    public void pack() {
        super.pack();
    }

    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        model_jLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Model_jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Knowledge Representation / Visualisation");
        getContentPane().setLayout(new AbsoluteLayout());

        model_jLabel.setIcon(new javax.swing.ImageIcon("E:\\PhD\\PhD\\PhDThesis\\PhDSoftwareApplication\\Environment\\MeKDaM\\src\\toolbox\\viewtools\\blank.png")); // NOI18N
        model_jLabel.setName("model_jLabel"); // NOI18N
        getContentPane().add(model_jLabel, new AbsoluteConstraints(28, 29, 1240, 770));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        Model_jTextArea.setColumns(20);
        Model_jTextArea.setRows(5);
        Model_jTextArea.setName("Model_jTextArea"); // NOI18N
        jScrollPane1.setViewportView(Model_jTextArea);

        getContentPane().add(jScrollPane1, new AbsoluteConstraints(10, 10, 1270, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ModelVisualization_JFrame("").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Model_jTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel model_jLabel;
    // End of variables declaration//GEN-END:variables
}
