/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModelVisualization_JFrame.java
 *
 * Created on 22-Jul-2011, 07:45:14
 */
package toolbox.viewtools;

import java.io.File;
import toolbox.Tools;

/**
 *
 * @author amb04
 */
public class TextModelVisualization extends javax.swing.JFrame {

    
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    public TextModelVisualization(String displayText) 
    {
        initComponents();              
        this.setVisible(true);
        if (displayText!=null)
        {                    
            Model_jTextArea.setText(displayText);
        }
//        else
//            System.out.println(" no text to be displayed");
    this.pack();
    this.repaint();
    }
   
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @Override
    public void pack() {
        super.pack();
    }

    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Model_jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new AbsoluteLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        Model_jTextArea.setColumns(20);
        Model_jTextArea.setRows(5);
        Model_jTextArea.setName("Model_jTextArea"); // NOI18N
        jScrollPane1.setViewportView(Model_jTextArea);

        getContentPane().add(jScrollPane1, new AbsoluteConstraints(10, 10, 920, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TextModelVisualization("").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Model_jTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
